### ISSUE TITLE
Amazon.Lambda.AspNetCoreServer.Hosting and LambdaTestTool

### ISSUE THREAD

**Issue by DerekBeattieCG** [aws/aws-lambda-dotnet#1018]
In a .NET 6 minimal API, should adding a ref to `Amazon.Lambda.AspNetCoreServer.Hosting` and using the extension method:
`builder.Services.AddAWSLambdaHosting(LambdaEventSource.HttpApi);`

work with the LambdaTestTool if `AWS_LAMBDA_FUNCTION_NAME` env variable is set?

**Comment by normj** [comment]
I'm assuming your are deploying with a .NET 6 container image since the managed .NET 6 runtime isn't released yet. .NET 6 Lambda functions that use top level statements and `Amazon.Lambda.AspNetCoreServer.Hosting` are not currently supported in the LambdaTestTool.

This is due to that fact `Amazon.Lambda.AspNetCoreServer.Hosting` and other Lambda functions that use top level statements are deployed as executables instead of class libraries that LambdaTestTool can load up and use reflection, based on the function handler string, figure out the piece of code to call.

I'm doing investigation to see how we can make the LambdaTestTool useful in the executable scenario. Some how the test tool needs to be able to invoke the assembly's entry point and mock out the Lambda runtime client HTTP API.
