### ISSUE TITLE
Publish DotNet 6.0 AWS Serverless Application fails

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#1019]
I have been able to create from scratch and deploy an AWS Lambda function for DotNet 6.0

But when it comes to an AWS Serverless application that I created from scratch (VS 2022 Version 17.0.2) when I try to publish I get

**error NETSDK1005: Assets file '...\project.assets.json' doesn't have a target for 'netcoreapp3.1'.**

AWS Toolkit is V 1.23.3.0

Project is
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>
    <!-- This property makes the build directory similar to a publish directory and helps the AWS .NET Lambda Mock Test Tool find project dependencies. -->
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer" Version="7.0.1" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="wwwroot\images\" />
  </ItemGroup>
</Project>
```

Anyone managed to deploy DotNet 6 AWS Serverless Application?

**Comment by normj** [comment]
Is this with the .NET 6 container image since we don't have the .NET 6 managed runtime out yet? If you have a `aws-lambda-tools-defaults.json` make sure you don't have a `framework` property set to netcoreapp3.1 in that file. It is actually best if you just remove the `framework` property from `aws-lambda-tools-defaults.json` and let the tool infer the framework from the project file.

**Comment by genifycom** [comment]
Thanks Norm. I will give that a try.

Looking forward to the .NET 6 managed runtime :)

**Comment by genifycom** [comment]
Any potential release date for the .NET 6 managed runtime?
