### ISSUE TITLE
Using .NET 6 minimal API with Dockerfile?

### ISSUE THREAD

**Issue by jbowtie** [aws/aws-lambda-dotnet#1032]
## The Question

The existing Dockerfile examples all seem to expect an explicitly created handler function to be passed as the CMD parameter.

However the minimal API example using `Amazon.Lambda.AspNetCoreServer.Hosting` seems to implicitly create the handler function. In this case, what should we supply as the CMD parameter if we want to use this with a Dockerfile? Or should we be overriding the ENTRYPOINT when using the minimal API?

**Comment by aaoswal** [comment]
Hi @jbowtie,
I am unable to find the case where the [minimal API](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-6.0) example using [`Amazon.Lambda.AspNetCoreServer.Hosting`](https://github.com/aws/aws-lambda-dotnet/blob/baa10d4788f339bd35137ea1b5c01df0a5b82afc/Libraries/src/Amazon.Lambda.AspNetCoreServer.Hosting/README.md) seems to implicitly create the handler function. 
Could you please provide a code sample for me to help you further?

**Comment by normj** [comment]
When using `Amazon.Lambda.AspNetCoreServer.Hosting` you are deploying you're Lambda function as an executable assembly. When deploying as an executable assembly the CMD should be the name of the assembly. So instead of `<assembly-name>::<type-name>::<function-name>` it would just be `<assembly-name>`.

Executable .NET assemblies is a new feature we have for .NET 6. There will be more information coming out about how to use this feature as we finish up the managed runtime.

**Comment by genifycom** [comment]
Hi Norm, in the case of Docker container for a Serverless Application, what do we put as the CMD in that case?

**Comment by pranavacharyafdb** [comment]
Hello, is there any example of Docker file which creates images of minimal dotnet APIs for deploying to AWS lambda? I am trying to find one but couldn't find any documentation.
