### ISSUE TITLE
Output of CultureInfo differs on local machine vs AWS

### ISSUE THREAD

**Issue by maximkiseliov** [aws/aws-lambda-dotnet#1045]
## Description
The issue is related to the output of CultureInfo object (https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.currentculture?view=net-6.0 ). Its output differs on the local machine from one which is generated on the AWS side despite the fact that it was created with the ignorance of UserOverride (useUserOverride = false). 
For example:
- for "en-GB" culture EXPECTED: the AM/PM bit for "h:mm tt" time format to be in upper case (e.g. 5:00 PM) ACTUAL: getting those in lower case (e.g. 5:00 pm). 
- for "zh-CN" culture the date is not translated to Chinese (it is translated when code runs locally). 

## Reproduction Steps
Code example:

```
        private static string FormatOpeningHours(DateTime startTime, string dateTimeFormat, string cultureName)
        {
            var cultureInfo = new CultureInfo(cultureName, false);
            return GetFormattedDateTime(startTime, dateTimeFormat, cultureInfo);
        }

        private static string GetFormattedDateTime(DateTime dateTime, string dateFormat, CultureInfo cultureInfo)
        {
            return dateTime.ToString(dateFormat, cultureInfo);
        }
```

Where:
- dateFormat - "yyyy MMMM dd"
- timeFormat - "h:mm tt"
- cultureInfo - "zh-CN" / "en-GB"

### Environment

* Build Version: 1.1.0
* OS Info: Windows 10 
* Build Environment: Visual Studio
* Targeted .NET Platform: .NET Core 3.1

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @maximkiseliov,

Good morning.

Could you please share the following to troubleshoot the issue:
- How you are executing the above code in AWS environment? I'm assuming it is AWS Lambda since the issue is logged in https://github.com/aws/aws-lambda-dotnet/ repository, just wanted to check.
- Detailed reproduction steps along with sample code solution.

I'm unsure if this issue is related to AWS SDK, but rather .NET related platform specific issue (kindly note that AWS Lambda runs on minimal Linux environment).

Thanks,
Ashish
