### ISSUE TITLE
AWS LAMBDA FUNCTION HANDLER FOR RABBITMQ -- RABBITMQEVENT class object

### ISSUE THREAD

**Issue by aboah** [aws/aws-lambda-dotnet#1048]
I would be very grateful if shown how I can install package for Amazon.Lambda.RABBITMQEVENT
This is to enable me build a function Event Handler for my Amazon RabbitMQ as an event source in dot net 
since AWS Lambda now supports Amazon MQ for RabbitMQ as an event source 
I refer to https://aws.amazon.com/about-aws/whats-new/2021/07/aws-lambda-now-supports-amazon-mq-for-rabbitmq-as-an-event-source/

**Comment by ashishdhingra** [comment]
Hi @aboah,

Good afternoon.

Thanks for posting guidance question. Looks like this is most likely a feature request since we don't have a package named `Amazon.Lambda.RabbitMqEvent`. However, implementing it should be simple by following pattern for existing event classes since these for most part are POCO model classes. Please let me know if you would be willing to contribute in the form of PR.

Thanks,
Ashish

**Comment by ashishdhingra** [comment]
We have implemented new [Amazon.Lambda.MQEvents version 1.0.0](https://www.nuget.org/packages/Amazon.Lambda.MQEvents/1.0.0).
