### ISSUE TITLE
Wrong .net core sdk version check

### ISSUE THREAD

**Issue by ThibaultGrg** [aws/aws-lambda-dotnet#1111]
## Description

I tried to run the New-AWSPowerShellLambdaPackage function which is using function _validateDotnetInstall, I have .net core 3.1 installed but receive the following error:

"The installed .NET Core SDK does not meet the minimum requirement to build the PowerShell Lambda package bundle. Download
the .NET Core 3.1 SDK from https://www.microsoft.com/net/download"

Turns out that the code in this function checks the current version against the version 6 of the .net core sdk and throws the above error message if it is below 6 (at line 604)

## Resolution

Just set back the line 604 to content before latest merge ($minVersion = [System.Version]::Parse('3.1.100')), it used to correctly compare the current version against version 3.1 until the last branch.

Thank you!

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @ThibaultGrg,

Good morning.

As part of latest release, AWSLambdaPSCore module was updated to target the .NET 6 Lambda runtime and use 7.2 PowerShell SDK as part of commit https://github.com/aws/aws-lambda-dotnet/commit/efba0de916d2a50f0143042106924e3131914546. So you need to have .NET 6.0 SDK installed in order to use latest `AWSLambdaPSCore` module. The exception thrown for minimum version at line https://github.com/aws/aws-lambda-dotnet/blob/0be7042f14d8603663fffebccdc20042b60bd359/PowerShell/Module/Private/_DeploymentFunctions.ps1#L622 appears to be a typo and needs to be corrected.

Thanks,
Ashish

**Comment by ppittle** [comment]
Looks like the error message will be updated in https://github.com/aws/aws-lambda-dotnet/pull/1096, which is pending release.

**Comment by ashishdhingra** [comment]
This should be fixed in [AWSLambdaPSCore 3.0.1.0](https://www.powershellgallery.com/packages/AWSLambdaPSCore/3.0.1.0).
