### ISSUE TITLE
Is AddAWSLambdaHosting only for minimal API or it will also work with AP IWith controllers

### ISSUE THREAD

**Issue by teenahjob** [aws/aws-lambda-dotnet#1152]
### Describe the issue

I have few question
a) AWS server less template for VS 2022 creates a project of type executable and adds LambdaEntryPoint ,LocalEntry Point with startup?
Why is it creating project type as an executable? Why is there no way of using Program.cs and we have to use Startup which is .net core 3.1 way of doing this.
Documentation is not clear. 
2)If I Create .net core API project and make LambdaEntryPoint,LocalEntryPoint to work with program.cs will it work.

Can someone quide?

### Links

This documentation is not for 6.1
https://github.com/aws/aws-lambda-dotnet/blob/ba7a655f8c316bdd078ef8b0db6b1746c61584e3/Libraries/src/Amazon.Lambda.AspNetCoreServer/README.md

**Comment by normj** [comment]
When we updated the templates for .NET 6 we did not change the existing ASP.NET Core template which has always had the 2 different entry point classes as you described. We thought there were lots of users already used to that style and there are a lot of docs and blog posts out in the wild describe how to build ASP.NET Core Lambda function that way. So we created a separate template using the Minimal API approach and using the new `AddAWSLambdaHosting` method for initialization.

Deploying executable assemblies which is required for `AddAWSLambdaHosting` was not supported in Lambda runtimes before .NET 6. Which is why we had to do the 2 different entry point pattern. 

You can deploy an ASP.NET Core application that is not using Minimal API using the `AddAWSLambdaHosting` as long as you deploy the application as an executable assembly. That means you need to change the function handler string in your CloudFormation template to just the assembly name instead of <assembly>::<type>::<function>.

**Comment by ashishdhingra** [comment]
@teenahjob Could you please check if input from @normj was helpful and provided necessary guidance, and if this issue could be closed?
