### ISSUE TITLE
APIGatewayCustomAuthorizerRequest missing RouteArn property

### ISSUE THREAD

**Issue by rackerWard** [aws/aws-lambda-dotnet#1278]
### Describe the feature

When working with an HttpApi custom Lambda authorizer 

The class APIGatewayCustomAuthorizerRequest is missing the property RouteArn.  
Add the property RouteArn to the APIGatewayCustomAuthorizerRequest class.

A custom authorizer is not able to access this data when using APIGatewayCustomAuthorizerRequest.
It is misleading to use MethodArn, which appears to never have a value assigned.

### Use Case

The RouteArn value can be used to specify the resource in the APIGatewayCustomAuthorizerPolicy

### Proposed Solution

Modify the class APIGatewayCustomAuthorizerRequest and add the following property.
`		public string RouteArn { get; set; }`

### Other Information

Create your own APIGatewayCustomAuthorizerRequest class and add the property to it.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

Amazon.Lambda.APIGatewayEvents v2.5.0

### Targeted .NET Platform

.NET 6

### Operating System and version

AWS Lambda Linux

**Comment by ashishdhingra** [comment]
Hi @rackerWard,

Good morning.

Thanks for submitting feature request. Could you please point to the API Gateway documentation which specifies support for `RouteArn` property for Lambda Authorizer? Lambda request classes are POCO classes and modeled according to the documentation. I was referring to the example at [Input to an Amazon API Gateway Lambda authorizer](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-lambda-authorizer-input.html), it does not specify use of `RouteArn`.

Thanks,
Ashish

**Comment by rackerWard** [comment]
Hi Ashish,

API Gateway has REST API and HTTP API.  The link you provided goes to the REST API documentation.  In the [https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-lambda-authorizer.html](Working with AWS Lambda authorizers for HTTP API) the payload format version 2.0 has `routeArn `and does not contain `methodArn` which is in the documentation under the REST API.

The following is an example of an API Gateway event sent to a Lambda function setup as an authorizer.

```
{
  version: '2.0',
  type: 'REQUEST',
  routeArn: 'arn:aws:execute-api:us-west-2:123456:abc/$default/POST/resource',
  identitySource: [ 'QbhY3Z+hyZ0iIAsuwjYppTbvVaBs9qgHZyvG1s4b4sg=' ],
  routeKey: 'POST /resource',
  rawPath: '/resource',
  rawQueryString: '',
  headers: {
    accept: 'application/json',
    'content-length': '485',
    'content-type': 'application/json; charset=UTF-8',
    host: 'abc.execute-api.us-west-2.amazonaws.com',
    'avdsa': 'QbhY3Z+hyZ0iIAsuwjYppTbvVaBs9qgHZyvG1s4b4sg=',
    'user-agent': 'Mozilla/5.0',
    'x-amzn-trace-id': 'Root=1-123-abcde',
    'x-forwarded-for': '76.x.x.x',
    'x-forwarded-port': '443',
    'x-forwarded-proto': 'https'
  },
  requestContext: {
    accountId: '123456',
    apiId: 'abc',
    domainName: 'abc.execute-api.us-west-2.amazonaws.com',
    domainPrefix: 'abc',
    http: {
      method: 'POST',
      path: '/resource',
      protocol: 'HTTP/1.1',
      sourceIp: '76.x.x.x',
      userAgent: 'Mozilla/5.0'
    },
    requestId: 'CABCBgWPvHcESLQ=',
    routeKey: 'POST /sessions',
    stage: '$default',
    time: '17/Aug/2022:17:15:31 +0000',
    timeEpoch: 1660756531128
  }
}
```

**Comment by andremantaswow** [comment]
Also looking forward to know how this should be used in C# lambda authorizers. I can't find a POCO class that represents the v2 payload of this documentation: https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-lambda-authorizer.html

cc @ashishdhingra

**Comment by ashishdhingra** [comment]
> Also looking forward to know how this should be used in C# lambda authorizers. I can't find a POCO class that represents the v2 payload of this documentation: https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-lambda-authorizer.html
> 
> cc @ashishdhingra

@andremantaswow Agreed, the current version of [APIGatewayCustomAuthorizerRequest](https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.APIGatewayEvents/APIGatewayCustomAuthorizerRequest.cs) doesn't appear to support [HTTP API 2.0](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-lambda-authorizer.html) payload version. Would you be willing to contribute a PR to fix this issue which could be reviewed by the team?

**Comment by andremantaswow** [comment]
@ashishdhingra what's the approach the team is expecting here? I see at least 2 options:

1) Update existing APIGatewayCustomAuthorizerRequest class to include not only v1 format fields but also the new v2 fields (so that deserialization from json works for both cases). Since people are only using it for v1 format (eg reading `request.MethodArn` in their code), we could make it a non breaking change even if the incoming payload is v2.
2) Create new class APIGatewayCustomAuthorizerRequestV2 with only the fields of v2 payload format. Then function handlers that are expecting to receive a v2 payload format would use it on the method signature. This has the disadvantage of needing two different lambdas, each pointing to different handlers in the project, if people want to slowly transition from v1 to v2 format.

I'm sure there are more options and that's why I'd like to get the team feedback before starting a PR in the wrong direction.

**Comment by ashishdhingra** [comment]
> @ashishdhingra what's the approach the team is expecting here? I see at least 2 options:
> 
> 1. Update existing APIGatewayCustomAuthorizerRequest class to include not only v1 format fields but also the new v2 fields (so that deserialization from json works for both cases). Since people are only using it for v1 format (eg reading `request.MethodArn` in their code), we could make it a non breaking change even if the incoming payload is v2.
> 2. Create new class APIGatewayCustomAuthorizerRequestV2 with only the fields of v2 payload format. Then function handlers that are expecting to receive a v2 payload format would use it on the method signature. This has the disadvantage of needing two different lambdas, each pointing to different handlers in the project, if people want to slowly transition from v1 to v2 format.
> 
> I'm sure there are more options and that's why I'd like to get the team feedback before starting a PR in the wrong direction.

CC @normj

**Comment by houseofcat** [comment]
@ashishdhingra @normj I recently implemented an AWS Lambda Authorizer, I have the contracts. It's wasn't as straight forward as I had assumed/hoped.

New `RestApi` and `HttpApi` created in the API Gateway both use the new `v2` payload/model. Legacy RestApis (i.e. ones not recently created since Api Gateway made this shift) are still using payload format `v1`. It's probably safe to assume new ones are of contract `v2` but perhaps its definitely worth a note to people under taking this trek. To make matters a bit more complicated, apparently there is a new non-IAM Policy authorization response, referred to as `Simple` that is effectively a `bool` of `isAuthenticated`.

Despite this, I can happily submit a PR for the models that did eventually work.

**Comment by andremantaswow** [comment]
@houseofcat any updates on the PR? thanks

**Comment by ashishdhingra** [comment]
@houseofcat / @andremantaswow The file https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.APIGatewayEvents/APIGatewayCustomAuthorizerV2Request.cs now has the `RouteArn` property. It was added in `Amazon.Lambda.APIGatewayEvents` version `2.6.0`. Could you please verify and confirm?

Thanks,
Ashish
