### ISSUE TITLE
How can I load appsettings.Development.json?

### ISSUE THREAD

**Issue by petro2050** [aws/aws-lambda-dotnet#1298]
In the constructor of `Startup.cs`, I injected an `IWebHostEnvironment` and noticed the environment is set to Production. This happens in debug mode. As a result, I'm unable to load `appsettings.Development.json`. I'm not sure if this is an issue on your end or .NET 6 / VS2022.

In `ConfigureServices`, I need to configure services based on the environment (for example use local DynamoDb in Development).

**Comment by normj** [comment]
Transferred to the .NET repo where the blueprints live.

**Comment by CamileDahdah** [comment]
Hi there,
The issue that you are talking about has to do with how Visual Studio's Test Runner operates. It is not related to the project itself (although having launchSettings.json in the test project is confusing because it is not being used). 
There is already a thread about this issue [here](https://github.com/aspnet/Tooling/issues/1089), it seems like the current workaround is to read the JSON file manually.
