### ISSUE TITLE
.NET 7 Lambda Test Tool Settings Missing

### ISSUE THREAD

**Issue by isaacrlevin** [aws/aws-lambda-dotnet#1362]
### Describe the bug

I recently updated VS, the AWS Extension, the Lambda templates, as well as the Lambda Global tools. One thing I notice when creating a new .NET 7 AOT project is that there is no option for the Mock Test tool in the Debug Options.

In order to fix this, I had to update the mock test tool (I thought it was in the overall global tool) as well as add the missing launch-settings for the project.

Also when thing I noticed is that the Mock test tool look in this folder 

`.\\bin\\$(Configuration)\\net7.0` (or net6.0 for that matter)

This is not the correct folder as the true path the built files are is

`.\\bin\\$(Configuration)\\net7.0\\win-x64`

### Expected Behavior

Upgrading to .NET 7 and using the templates should include Lambda Mock Test Tool

### Current Behavior

Unable to use Lambda Mock Test Tool with .NET Native AOT projects

### Reproduction Steps

After installing .NET 7 and updating everything, create a new .NET 7 Native AOT project

### Possible Solution

Add launch-settings file to .NET 7 Native AOT and Custom Runtime template

### AWS .NET SDK and/or Package version used

Amazon.Lambda.Templates::6.7.0

### Targeted .NET Platform

.NET 7

### Operating System and version

Windows 11

**Comment by normj** [comment]
The test tool will only be configured by VS if the Lambda project is class library used for either managed runtime or image based deployments. In that case the test tool can act as the Lambda runtime client and invoke the specified method. In the case of Native AOT the project is an executable which spins up its own Lambda runtime client so the default VS test tool integration doesn't work.

There is a page in the tool for executable assembly testing. It still needs a bit of work, this tool is preview, because right now you have to manually start the tool from the build output directory which you shouldn't have to do. Plus this executable assembly mode needs more docs.

**Comment by ik130** [comment]
This is an expected behavior, as such this issue will be closed.
