### ISSUE TITLE
Build Failure For .NET 7 AOT When Using A Private Package Source

### ISSUE THREAD

**Issue by mark-mybaggage** [aws/aws-lambda-dotnet#1400]
### Describe the bug

I've been following [this AWS article](https://aws.amazon.com/blogs/compute/building-serverless-net-applications-on-aws-lambda-using-net-7/) to build a Lambda function target .net 7 AOT.  I've a test function [here](https://github.com/mybaggage/test7).  The function uses a dll from a private nuget source (GitHub Packages) which is causing a build error.

A GitHub Action is used to build and deploy the function.  This is working well for all of our other Lambda functions.  The latest run is [here](https://github.com/mybaggage/test7/actions/runs/3693943738)

I'm using actions/setup-dotnet@v1 to setup the private nuget soource with auth token.  The path of the generated nuget.config file is:

/home/runner/work/test7/test7/nuget.config

dotnet lambda deploy-function is used to deploy the function.  The docker command generated froom ths is:

... invoking 'docker run --rm --volume "/home/runner/work/test7/test7/Test7":/tmp/source/ --name tempLambdaBuildContainer-9c36afdc-3033-4d52-87ee-6361e5207d05 -i public.ecr.aws/sam/build-dotnet7:latest-x86_64 dotnet publish "/tmp/source/Test7" --output "/tmp/source/Test7/bin/Release/net7.0/publish" --configuration "Release" --framework "net7.0" /p:AssemblyName=bootstrap --self-contained true /p:GenerateRuntimeConfigurationFiles=true --runtime linux-x64 /p:StripSymbols=true' from directory /home/runner/work/test7/test7/Test7

the --volume is created 1 folder too high and the nuget.config file is not included.  Is there a way to control the --volume parameter or set it to the root of the project?

### Expected Behavior

The value of --volume matches the root of the project, in this case:

home/runner/work/test7/test7

### Current Behavior

The value of --volume appears too be hardcoded one folder too high:

home/runner/work/test7/test7/Test7

### Reproduction Steps

Rerun the latest run of the GitHub Action:

https://github.com/mybaggage/test7/actions/runs/3693943738

### Possible Solution

Make --volume configurable

### AWS .NET SDK and/or Package version used

Amazon.Lambda.Core 2.1.0

### Targeted .NET Platform

.net 7

### Operating System and version

Ubuntu 22.04.1

**Comment by ashishdhingra** [comment]
Hi @mark-mybaggage The error I see in the failed GitHub action is `docker run: /tmp/source/Test7.csproj : error NU1101: Unable to find package MBCommon. No packages exist with this id in source(s): nuget.org [/tmp/source/Test7.sln]`. As your pointed out, `MBCommon` doesn't appear to be valid package at https://www.nuget.org/ and your are using the private GitHub source.

Looking at the Github action run, 
- The `Checkout repository` step is cloning the repository at `/home/runner/work/test7/test7'`.
- The `Build project` step is building the project at `/home/runner/work/test7/test7/Test7/`. So your project root appears to be `/home/runner/work/test7/test7/Test7/`.
- The AWS CLI Extension `dotnet lambda deploy-function -pl ./Test7` command is hence setting the project location and the Docker command `docker run --rm --volume "/home/runner/work/test7/test7/./Test7"` generated appears to be correct.

Assuming that the `nuget.config` (with private package source) works for you locally, wouldn't it be possible for `actions/setup-dotnet@v1` to generate the `nuget.config` at `/home/runner/work/test7/test7/Test7/`, instead of `/home/runner/work/test7/test7/`? Also, if this is the case, then ideally the GitHub action should run after clone repo step.

Unfortunately, we are unable to provide any guidance on GitHub action.

Thanks,
Ashish

**Comment by mark-mybaggage** [comment]
Hi @ashishdhingra, thanks for your reply.  All of the Github Actions reference were just for completeness.  I was really wondering if there was a way to change the --volume value

What I've ended up doing in adding the following to my Setup .NET step

```
 - run: |
          mv '${{ github.workspace }}/../nuget.config' '${{ github.workspace }}/${{env.PROJECT_NAME}}/nuget.config'
```

Doing this allow the build within Docker to succeed - it still feels a little brittle.  I've asked a question on actions/setup-dotnet@v1 if it's possible to change the output location
