### ISSUE TITLE
 Unable to find valid bootstrap(s) when invoking the function

### ISSUE THREAD

**Issue by RamakrishnanRajaram** [aws/aws-lambda-dotnet#1671]
### Describe the bug

We are migrating from .Net 6 to .Net 8 using custom runtime. When publishing a Lambda function from the Visual Studio using "Publish to AWS Lambda", it's working fine. But when I try to change the .Net version and zip the solution using dotnet lambda package then my function is failing to execute. I am getting the below error.
{
  "errorType": "Runtime.InvalidEntrypoint",
  "errorMessage": "RequestId: 2906f925-d972-4949-afdc-af42e3d5c90c Error: Couldn't find valid bootstrap(s): [/var/task/bootstrap /opt/bootstrap]"
}

### Expected Behavior

Function should execute succesfully

### Current Behavior

Facing the below error

{
  "errorType": "Runtime.InvalidEntrypoint",
  "errorMessage": "RequestId: 2906f925-d972-4949-afdc-af42e3d5c90c Error: Couldn't find valid bootstrap(s): [/var/task/bootstrap /opt/bootstrap]"
}

### Reproduction Steps

Create a lambda function. Zip the function using the dotnet lambda package and upload the zip file

### AWS .NET SDK and/or Package version used

AWSSDK 3.7.302.6

### Targeted .NET Platform

.Net 8

### Operating System and version

Amazon Linux

**Comment by normj** [comment]
If you are deploying to `provide.al2023` or `provided.al2` you need to deploy your Lambda project as a self contained executable. You also need to name your assembly as `bootstrap` because Lambda works in those runtimes by looking for an executable called `bootstrap` and executing it. If you look in our custom runtime project templates we set the `AssemblyName` property to `bootstrap`. https://github.com/aws/aws-lambda-dotnet/blob/master/Blueprints/BlueprintDefinitions/vs2022/CustomRuntimeFunction/template/src/BlueprintBaseName.1/BlueprintBaseName.1.csproj#L8C6-L8C18

**Comment by stoicad** [comment]
any updates on this topic? we are facing the same error

**Comment by normj** [comment]
I responded back with some things to try but never heard back how things worked out so the issue was closed for being stale. @stoicad You should open a new issue and describe how you are creating your bundle, what runtime you are deploying to and what you are setting the function handler to when deploying.
