### ISSUE TITLE
AWS Lambda requires extra dependencies?

### ISSUE THREAD

**Issue by megamindbrian** [aws/aws-lambda-dotnet#173]
I thought Kestrel already does this, why not just implement that interface for booting?

https://aws.amazon.com/blogs/developer/deploy-an-existing-asp-net-core-web-api-to-aws-lambda/

Not to draw attention away from these other blocking issues:
https://github.com/aws/aws-lambda-dotnet/issues/172
https://github.com/aws/aws-lambda-dotnet/issues/171

**Comment by normj** [comment]
Kestrel is not an interface, it is an implementation of the Microsoft.AspNetCore.Hosting interfaces. Since Kestrel is a webserver constantly listening for requests that doesn’t make sense in a Lambda/APIGateway context. So the little bit of code that you need to put in your project is to replace the default implementation of Microsoft.AspNetCore.Hosting to our implementation. All other code in the ASP.NET Core project is left alone and has nothing Lambda specific.
