### ISSUE TITLE
Build error "stack trace Index was out of range. Must be non-negative and less than the size of the collection."

### ISSUE THREAD

**Issue by werebear73** [aws/aws-lambda-dotnet#1743]
### Describe the issue

While building an .net AOT lambda I received this error that also asked for a verbose build and to open an issue

The build output is located at [gist](https://gist.github.com/werebear73/118107cf5b1380c210e16ac705c6e4ee)

### Links

[https://github.com/aws/aws-lambda-dotnet/blob/master/README.md](https://github.com/aws/aws-lambda-dotnet/blob/master/README.md)

**Comment by ashishdhingra** [comment]
@werebear73 Good morning. Looks like you used the wrong template to raise an issue. Could you please share the details in the below template:

### Describe the bug

### Expected Behavior

### Current Behavior

### Reproduction Steps

### Possible Solution

### Additional Information/Context

### AWS .NET SDK and/or Package version used

### Targeted .NET Platform

### Operating System and version
___
Thanks,
Ashish
