### ISSUE TITLE
Tool returns successful status when Cloudformation fails

### ISSUE THREAD

**Issue by matthewyost** [aws/aws-lambda-dotnet#1796]
### Describe the bug

When using the Amazon.Lambda.Tools (v5.10.5) and deploying a lambda package, if the package has certain issues with the Cloudformation, it will fail but return an exit code of 0.

Examples:
![image](https://github.com/user-attachments/assets/47774b62-39b1-4f01-8dcf-01cec1dbe061)
![image](https://github.com/user-attachments/assets/6551a876-6e21-4203-9d8b-4a911dc5fcb4)

### Expected Behavior

I would expect that if the cloudformation fails for any reason that we would receive a non-zero error code being returned to let us know that a failure occurred.

### Current Behavior

Currently, it fails silently not making users who aren't reading the logs of the deployments aware that something has failed.

### Reproduction Steps

Create a CloudFormation template where there is unresolved resource dependency in the Resources block of the template and then execute it.

### AWS .NET SDK and/or Package version used

Amazon.Lambda.Tools v5.10.5

### Targeted .NET Platform

.NET 8

### Operating System and version

Ubuntu 20.04

**Comment by matthewyost** [comment]
That didn’t work for me if it was set to true:

/home/ubuntu/Agent01/_work/_temp/awsshellscript_1123355.sh: line 3: --stack-wait: command not found

**Comment by ashishdhingra** [comment]
@matthewyost Thanks for your reply. Please share the below information:

- Share minimal reproducible code sample to reproduce the issue.
- How are you executing `dotnet lambda deploy-serverless` command? Is it executed via some shell script since per log screenshot, you appear to capture the exit code of bash? (**This appears to be the case per your last response**) 
  - Could you check if your script is returning `0`?
  - Share minimal snippet of your shell script.
  - For testing, could you execute `dotnet lambda deploy-serverless` command outside the shell script and inspect the output of `echo $?` command (this should return exit code of last command executed)?

Thanks,
Ashish
