### ISSUE TITLE
deploy-function says it doesn't support `netcore1.0`

### ISSUE THREAD

**Issue by adamhathcock** [aws/aws-lambda-dotnet#19]
here's the error I get now:
```
Error creating Lambda function: 1 validation error detected: Value 'netcore1.0' at 'runtime' failed to satisfy constraint: Member must satisfy enum value set: [java8, nodejs, nodejs4.3, python2.7]
```

I'm not sure what's reporting this.  Thought it maybe was the AWS CLI so I updated that.  But it looks like the AWS SDK is used anyway.  

I'm using eu-west-1 which definitely supports C#

Side question:  when can we get netcore1.1? :)

**Comment by normj** [comment]
The function runtime value to pass to Lambda should be "dotnetcore1.0" not "netcore1.0". I'll let the Lambda team know the error message is out of date and needs to include dotnetcore1.0 in it.

**Comment by normj** [comment]
As far as netcore1.1 I can't say anything about release timing. Something to keep in mind though is Lambda's runtimes are based on LTS, long term supported, versions of the runtime which is why we started with 1.0. The netcore1.1 version is considered FTS which means it will have a short support cycle once the next version comes out.

https://www.microsoft.com/net/core/support

**Comment by richardnagle** [comment]
Please also update the [readme](https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.Tools#manage-command-arguments-with-aws-lambda-tools-defaultsjson) where the wrong runtime value is specified in the  `aws-lambda-tools-defaults.json`

**Comment by normj** [comment]
Thanks, I updated the readme.

**Comment by Kralizek** [comment]
maybe we should add mention to `function-name` and `function-role` ? that makes the usage of `deploy-function` trivial
