### ISSUE TITLE
ASP.Net Core applications running in Lambda as proxy functions should not depend on URL resource paths

### ISSUE THREAD

**Issue by ddrinka** [aws/aws-lambda-dotnet#196]
Background
---------
Amazon.Lambda.AspNetCoreServer implements a handler between AWS API Gateway and a .Net Core Lambda function which runs ASP.Net Core.  The module's job is to translate between API Gateway's proprietary JSON formats and ASP.Net's request/response functionality.

API Gateway allows the creating of a virtual hierarchy of Resources and Methods.  A Proxy Resource acts as a wildcard, matching a provided url prefix, and passing the remainder of that url on to the configured ANY Method, in this case a .Net Lambda function.

This functionality is useful for aggregating multiple Lambda functions into a more complex exposed API, and also for versioning.  For instance, requests to `/v1/myapi` could be delivered to one Lambda function, while `/v2/myapi` could be delivered to another Lambda function.

Issue
----------
The ASP.Net Core backend should not need to be aware of its location in the API Gateway hierarchy, or aware of which published version it is currently running as.  However, with the current implementation, the full path from the root of the API Gateway to the end of the replaced wildcard proxy is provided as the Request.Path, and is routed accordingly.

Expected Behavior
----------
Given `/v1` and `/v2` are Proxy Resources, a request to `/v1/mycontroller/mymethod` should route in ASP.Net Core to `mycontroller/mymethod`, as should a request to `/v2/mycontroller/mymethod`.

Current Behavior
-----------
A request to `/v1/mycontroller/mymethod` routes to `v1/mycontroller/mymethod`, and a request to `/v2/mycontroller/mymethod` routes to `v2/mycontroller/mymethod`.

Resolution
-------------
Issue #127 asked a similar question, which was resolved with https://github.com/aws/aws-lambda-dotnet/commit/2949c9c87c3e87ac6484f88dc8aeb2b0db63a2b3.  However, https://github.com/aws/aws-lambda-dotnet/commit/0a3fb00cfb6f09d14618e7ff2544ce0478c9b7b0 effectively reverts that change.

Here is a workaround that solves this issue for me: https://gist.github.com/ddrinka/8418fef0fcc6f9455dd2c01f645560c6.  Include `app.UseProxyPath()` before `app.UseMvc()` in `Startup.cs`.

However I believe this should either be configurable in builder.UseApiGateway, or should default to what I see as the more common use case, as described above.

**Comment by normj** [comment]
If I'm understanding your issue you are proposing that if I defined my api gateway like this

/v1/{+proxy}
and
/v2/{+proxy}

When a request something like http://mygateway/PROD/v1/mycontroller you are expecting /mycontroller to be the root in ASP.NET Core because that is the proxy?

If so that is not how I intended that to work. I always wanted to root of the API Gateway stage to be the root in ASP.NET Core. I was imaging in most cases users would have the {+proxy} at the root but they might want to add sub proxies resources to use API Gateway's security features at certain paths or use a less memory for certain paths. This becomes more important as you have Lambda serve up a full ASP.NET Core web app which will be a feature of the upcoming .NET Core 2.0 release.

I don't disagree with our use case its just not what I wanted by default. I'm not opposed to a pull request or turning this into a feature request for enabling an options you can set from your derived APIGatewayProxyFunction that changes the behavior of how the root is computed.

**Comment by ddrinka** [comment]
You understood my issue.  The relationship that's set between API Gateway and Lambda is that every Lambda function becomes a mini web server.  That server might be handling a subset of requests, it might be a different version of the API, or it might be using a different language altogether.  API Gateway lets you piece together multiple components that define a single API.

My viewpoint is that the web server shouldn't have to be aware of where it lives in the API hierarchy, as it's a small piece of the puzzle.  The job of API Gateway is to abstract away from the code the concept of the hierarchy, filling in the functionality along the hierarchy with independent implementations.

So to me, defaulting a web server to being agnostic of the greater hierarchy makes the most sense.

That said, if the design intention was to have ASP.Net Core rooted at the stage, my request to make the default sensible from my perspective would be a breaking change, so we should just make an optional argument and keep moving.  :)

Once 2.0 is here on Github I'll do the work and make a PR.

**Comment by normj** [comment]
As part of the .NET Core 2.0 release today, https://aws.amazon.com/blogs/developer/aws-lambda-net-core-2-0-support-released/, I added some virtual methods to `APIGatewayProxyFunction` that you can overwrite and customize how the path is configured. For example you would overwrite the `PostMarshallRequestFeature` method and compute the path and base path as you like.

**Comment by normj** [comment]
I'm going to close this as I believe the virtual methods added to the latest version will provide you the hooks you need to make the changes you want.
