### ISSUE TITLE
Which DotNet Core 2.0 versions are supported

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#208]
I see Microsoft have already bumped DotNet Core 2.0 to 2.0.2

Before we go running into the same issues we had with DotNet Core 1.0 can you please advise which version of packages will be supported on Lambda.

Thanks,
Dave

**Comment by normj** [comment]
There are a lot of different version numbers in the .NET Core space so I'm not sure what exactly you are saying is 2.0.2.

Lambda is currently running .NET Core 2.0.4 of the runtime. Version 2.0.5 of the runtime came out while we were rolling our deployments. We will get Lambda up dated to that soon.

The good think in .NET Core 2.0 is the exact versions our not as important. The main issue in .NET Core 1.0 was that dependency NETStandard.Library which locked libraries to specific versions of the runtime. In .NET Core 2.0 that dependencies no longer exists and it is just an implied dependency that the API of .NET Standard 2.0 is available to the library.

**Comment by Kralizek** [comment]
> Lambda is currently running .NET Core 2.0.4 of the runtime.
Does it mean that Lambda supports up to version 2.0.4 of packages like Microsoft.AspNetCore.All ?

**Comment by normj** [comment]
The **Microsoft.AspNetCore.All** package is about the only thing you will notice a difference about not having 2.0.5 in Lambda yet. If your Lambda function puts a dependency on **Microsoft.AspNetCore.All** for version 2.0.5 that will fail because when the function executes it will look for the NuGet packages in Lambda that are part of the **Microsoft.AspNetCore.All** package. Till Lambda is updated to 2.0.5 you need to reference version 2.0.3 of **Microsoft.AspNetCore.All**. There was no version 2.0.4 of **Microsoft.AspNetCore.All**. The VS tooling and our dotnet CLI extension will fail the deployment if you try to reference a version of **Microsoft.AspNetCore.All** that is not yet available in Lambda.

**Comment by ytn3rd** [comment]
@normj Even though you said it doesn't really matter, is there any page on AWS or specific commands we could run inside a lambda function to see what runtime version is currently running?

**Comment by dls314** [comment]
@Kralizek @normj 

I haven't tried it, but It may be possible to specify the `<PublishWithAspNetCoreTargetManifest>false</PublishWithAspNetCoreTargetManifest>` flag to treat at least the ASP.NET Core (as opposed to .NET Core) related dependencies as self-contained for your application while still using the Microsoft.AspNetCore.All metapackage.

See, links for more:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage
https://docs.microsoft.com/en-us/dotnet/core/deploying/runtime-store

**Comment by normj** [comment]
@ytn3rd There is nothing AWS provided to determine the runtime version. You could probably check assembly versions but that will get tricky as assembly versions numbers are versioned independently of the overall .NET Core version.

I believe the original question is answered so I'm going to close the issue.
