### ISSUE TITLE
Move the code out of the APIGatewayProxyFunction in a 'start' method!

### ISSUE THREAD

**Issue by arndklocker** [aws/aws-lambda-dotnet#227]
I want to set a variable in my derived class, but at the moment the default constructor is called and all other methods are initialized before my variable in the derived class is set. Is it possible to move the code out of the consturctor in a 'start' method?

Background: I want to set the 'ASPNETCORE_ENVIRONMENT' with the 'InvokedFunctionArn' from 'ILambdaContext'. I have an working implementaton, but I made the changes in my local repository.

**Comment by normj** [comment]
I'd recommend in your derived class to overwrite the `PostCreateContext` method and set the environment variable in that. There are several other PostX methods that you can overwrite to customize the transformation from API Gateway to ASP.NET Core.

**Comment by arndklocker** [comment]
`PostCreateContext` is to late, this method is called in `FunctionHandlerAsync`. I want to set some varialbes before the base constructor does initializing.

`protected APIGatewayProxyFunction(bool autostart = true)
        {
            if(autostart)
            {
                Start();
            }
        }`

**Comment by normj** [comment]
Okay so the code in question is here: https://github.com/aws/aws-lambda-dotnet/blob/0bf318e67ae269e10e61f65811711fafd25d029c/Libraries/src/Amazon.Lambda.AspNetCoreServer/APIGatewayProxyFunction.cs#L83-L97

I assume what your need is have the environment variables set before the WebHost is built, possibly because it affects how the configuration object is built.

And what you need is this code in the constructor to be delayed till the first function invocation with a hook for you to run some code before that with the ILambdaContext. I'd rather not expose the start method because I could see people miss understanding it and calling it for every function invocation and wonder why everything is running so slow. Here is what I think I could do:

- Move the code into a new private start method
- Constructor takes in a autoStart or delayStart boolean, not sure what name I like better, with the default keeping the existing behavior
- Add a new empty virtual method called before processing the request which you could overwrite to set the environment variables.
- In the FunctionHandlerAsync call the new empty virtual method first.
- If the WebHost builder is null then run the new private start method.
- Continuing processing request as done today.

If that works for you I think I can make those changes. Unfortunately I won't be able to get to that till late next week.

**Comment by arndklocker** [comment]
Yes sounds good. Can you make a new nuget package with this feature?

**Comment by arndklocker** [comment]
When will it be done? With this fix, many other current issues can be fixed in derived classes by the community e.g. "set environment at startup"

**Comment by normj** [comment]
Fix with PR https://github.com/aws/aws-lambda-dotnet/pull/267
