### ISSUE TITLE
Publishing Static Files to S3

### ISSUE THREAD

**Issue by Pelias2525** [aws/aws-lambda-dotnet#250]
Since modification of static files such as images, javascript, and css are a large part of the development lifecycle and [it is recommended](https://aws.amazon.com/blogs/developer/serverless-asp-net-core-2-0-applications/) that developers store those static files in S3 instead of being accessed directly through lambda, would it be possible, as part of the publication process, to specify an S3 bucket for those static files to go into so that those resources don't need to be uploaded manually every time there is a new website deployment?

**Comment by normj** [comment]
I agree this is an important feature we need to smooth out the work flow for running web apps on Lambda.

**Comment by Xymanek** [comment]
Any news on this? Or perhaps an alternative?

**Comment by msimpsonnz** [comment]
An alternative might be CDK which can be used to  create template to upload assets to S3 and also define Lambda functions
https://docs.aws.amazon.com/cdk/api/latest/dotnet/api/Amazon.CDK.AWS.S3.Deployment.html

**Comment by Xymanek** [comment]
Interesting, I was not aware of CDK. It does seem more flexible (even if less plug-and-play 😄), I will definitely give it a go

**Comment by normj** [comment]
Given the change in tooling since this issue was created I don't think adding this feature into the Lambda tooling makes as much sense. Then we have to expand the .NET Lambda tooling to also manage CloudFront distributions and S3 buckets. I think the CDK or our newer [general .NET deploy tool](https://github.com/aws/aws-dotnet-deploy/) which manages Blazor WebAssembly deployments are better solutions for static file uploads.
