### ISSUE TITLE
Support for Binary Data using Razor Pages

### ISSUE THREAD

**Issue by mattleigh** [aws/aws-lambda-dotnet#279]
I have created a new Visual Studio project using the Serverless Razor Pages template provided by the AWS SDK. It works fine when I run it locally, but after deploying it images referenced via html img tags cannot be displayed (I am using a jpeg image in my project for testing). I believe this is due to the support for binary files not being configured correctly.

Steps to reproduce:
1. Create a new VS project using Serverless Razor Pages template
2. Add a jpeg image to the project
3. Display the jpg in an img tag
4. Deploy to Lambda

According to this page

> If your web application displays images, we recommend you serve those images from Amazon S3. This is more efficient for returning static content like images, Cascading Style Sheets, etc. Also, to return images from your Lambda function to the browser, you need to do extra configuration in API Gateway for binary data.

I have added the image/jpeg to the Binary Media Types in the API Gateway settings but they are still not being served correctly. If I try hitting the image path directly from the browser I get "The image {image path} cannot be displayed because it contains errors.". If I retrieve the image using Powershell it looks like the content is an array of integers.

a. Can anyone tell me what I'm doing wrong?
b. If this is an issue around the Binary Media Type configuration, can the required config be added to the serverless.template file in the Razor Pages VS template

**Comment by axel-zarate** [comment]
I think it has to do with API Gateway not receiving the right `Accept` header. You can refer to [this thread](https://forums.aws.amazon.com/thread.jspa?threadID=243499).

I don't think there is a direct solution to that if you are requesting the resource via the browser, `img` tag, etc., where you have no control over the request headers. That's why the suggested solution is to serve static content from S3. This is a good idea not only because of the limitations of serving binary data, but because of the overkill of the process to serve the files (load them into memory, serialize them in the JSON response, etc.), not to mention the lack of caching.

**Comment by normj** [comment]
In the API Gateway Console you can specify what content types to return binary. You can also use a wild card for example **image/***

![image](https://user-images.githubusercontent.com/1653751/40445617-7f8bed92-5e81-11e8-8cbd-0fca3a0967b7.png)

**Comment by mattleigh** [comment]
I have tried adding the Binary Media Type as above.  I still get the same error.  

Should this setting take effect immediately?

**Comment by ashishdhingra** [comment]
Hi @mattleigh,

Good morning.

I was going through the issue backlog and came across this guidance question. Please let me know if this still an issue or if this could be closed.

Thanks,
Ashish
