### ISSUE TITLE
Stages in API Gateway

### ISSUE THREAD

**Issue by justinhelgerson** [aws/aws-lambda-dotnet#312]
I have two questions related to stages in API Gateway:

1. When deploying via `dotnet lambda deploy-serverless` it automatically creates the stages `Prod` and `Stage`.  Where do these come from?  It's not defined anywhere in my template, but I can see these values in the processed template in Cloud Formation.
2. Related to #167, I'd like to specify the stage that gets updated during our deployments so we can deploy to a "test" stage first and then finally deploy to a "production" stage.  However, the `AWS::Serverless::Api` resource requires a `DefinitionUri` or `DefinitionBody` property, neither of which I have a need for.  How can I define and specify my own stages?

**Comment by justinhelgerson** [comment]
After further research for 1. above, it looks like a bug that can't easily be resolved:  https://github.com/awslabs/serverless-application-model/issues/191.

Still looking for advice on 2. though.

**Comment by normj** [comment]
As you saw the AWS::Serverless::Api gets transformed into lower level CloudFormation resources with the stage and prod stages defined. If you want to do something different then you might want to look at using the lower level CloudFormation resources instead of AWS::Serverlesws::Api. A good starting point for that would be doing a deployment using the AWS::Serverless::Api resource and then once deployed you can look at the transformed template in the web console where you can see how the stages are defined. Take that template and then customize it.

**Comment by KenHundley** [comment]
I have a suggestion that kind of meets in the middle. For our projects we use the AWS::Serverless::Function type (without defining API events) instead of Api, and then define the rest of the resources in the template, like the API Gateway and Stages. This gives us a lot of the added functionality that the SAM brings, but also gives us much more freedom when creating the API Gateways, Stages, etc. 

Going this route does require you to explicitly define the Gateway, Stages, etc in the templates, handle all the mapping between API Gateway and Lambda, setup Lambda Permissions so that it can be executed by API Gateway, etc, but I personally find it a good middle ground between simplicity of SAM/AWS::Serverless::Api and flexibility you get when creating all the objects explicitly.

https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

**Comment by normj** [comment]
Closing as I believe this has been answered the best we can from this repo
