### ISSUE TITLE
HttpClient is slower inside Lambda

### ISSUE THREAD

**Issue by popsovy** [aws/aws-lambda-dotnet#316]
Hello, I noticed that performance of HttpClient inside Lambda is considerably slower than that of a console app. For example, this code inside of Lambda executes in around 5 seconds:

```
        public async Task FunctionHandler(ILambdaContext context)
        {
            await Task.WhenAll(Enumerable.Range(0, 1000).Select(i => Get(i)));
        }

        System.Net.Http.HttpClient client = new System.Net.Http.HttpClient();
        async Task Get(int i)
        {
            await client.GetAsync("http://httpclient1.azurewebsites.net/");
        }
```

The same code inside DotNet 2.1 console app (running in the Release mode from a command prompt, not in IDE), executes in about 200 milliseconds. That's 25 faster.

Do you have any ideas why my test inside of the Lambda function is so much slower. Please note http://httpclient1.azurewebsites.net is just a test Azure site that has the default Azure page.

Thank you for your help.

Evgueni

**Comment by vellozzi** [comment]
Lambda functions are run in a memory and CPU constrained environment.

It's almost impossible to compare the two environments.  I would expect most code to run a bit slower in Lambda.  I'm not sure what might account for the 25x difference though.

If you need your Lambda function to run faster try increasing it's memory size.  The name is misleading because a larger memory size also corresponds to a higher CPU rate limit.

Try different values for memory size and see if that 25x factor comes down.

**Comment by popsovy** [comment]
Changing memory to 2048 MB did not have an effect on performance of this Lambda function -- it still completes in about 5 seconds.

**Comment by PaulColeman** [comment]
Can you change your code to do a single Get and tell us how long that takes
please? I suspect most of the cost you are seeing is some initialization
overhead. But let's see the results of just doing one http call.

**Comment by popsovy** [comment]
Changing the code to a single Get brings execution down to 100 ms.

**Comment by popsovy** [comment]
I had bad code in my Console test -- the Task.WhenAll needed the .Wait() in the static method. Once I added Wait() in the Console app, the duration went up to around 5 seconds. So, it's not a problem with Lambda. Operator error :). My bad. Thanks for your help.
