### ISSUE TITLE
Asp.net core 2.2 support in Lambda 

### ISSUE THREAD

**Issue by PaymonK** [aws/aws-lambda-dotnet#356]
It seems the latest version of .net supported in Lambda is 2.1.4. That is causing compatibility problems for us. 

When will 2.1.5 or ideally 2.2 be supported?

**Comment by normj** [comment]
Lambda is currently running 2.1.5 which you can see from our [version status table](https://github.com/aws/aws-lambda-dotnet#version-status).

Out of curiosity what were the compatibility problems?

**Comment by PaymonK** [comment]
Apologies, I didn't notice that 2.1.5 was now supported. My data was a few days old.
We were experiencing problems running 2.1.4 in development mode in general. Nothing to do with Lambda actually.

**Comment by ZeinSleiman** [comment]
What about 2.2?The version table still mentions 1.17 as Microsoft latest release.

**Comment by vellozzi** [comment]
That means it's the latest patch of the corresponding minor version. E.g. 1.0.13 is the latest patch of 1.0.

We're only planning to support LTS versions of .NET Core.  .Net Core 2.0 was an exception to that because at the time we believed it was going to be LTS.

We are talking about how we might help customers work with Lambda's [custom runtime](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-custom.html) feature though.  But we don't have an ETA for that work.

**Comment by michelmob** [comment]
Hi guys! I know this thread is closed but would like to hear from you guys if we already have another solution/workaround. 

I have some lambda functions running using .net core 2.1 but I had to update my applications to .net core 2.2 and got in the hell with other packages.

I got the documentation to use custom runtime but I would like to understand what options I have. Can you guys help me ?

Thank you so much!

**Comment by normj** [comment]
@michelmob I suggest following this GitHub issue tracking our effort to open source our .NET Core Lambda runtime code.

**Comment by RoyiNamir** [comment]
https://github.com/aws/aws-lambda-dotnet/issues/356#issuecomment-445323158

I don't understsand.
This article : 
https://aws.amazon.com/blogs/developer/announcing-amazon-lambda-runtimesupport/

Says that 2.2 is supported.

What am I missing ?

**Comment by clearwaterstream** [comment]
@RoyiNamir, out-of-box currently only 2.1 is supported, 2.2 is not.

You can deploy an app running on 2.2 using a custom runtime. Read high level intro [here](https://aws.amazon.com/blogs/developer/announcing-amazon-lambda-runtimesupport/) and see an example app [here](https://github.com/normj/LambdaNETCoreSamples/tree/master/CustomRuntimeAspNetCore)

I would like to note that apps using a custom runtime do take longer to deploy. It's not the extra files that make the deployment longer, I think it's the warm-up or initialization post deploy that's taking the extra time.

You could wait for AWS .NET team to release ASP.NET Core 2.2 support but by the time they do, 3.0 may be out and you will end up in the same boat again -- waiting. So may not be a bad idea to invest in setting up a CustomRuntime now.

Over the years, I've waited for AWS to release .NET 4.7.2 way back when they were running on 4.7, it took a while. Had to custom bootstrap our Elastic Beanstalk instances with 4.7.2. I've also waited for 2.1. So going forward, I'll roll with CustomDeployment so that I can have more control over the infrastracture.

**Comment by petarrepac** [comment]
I think AWS announced they will support only LTS .NET Core releases. The only exception for now was .NET Core 2.0.
* 2.1 is LTS
* 2.2 in not LTS.
* 3.0 will be released in September 2019 and is not LTS
* 3.1 will be an LTS, coming in November 2019

more here: https://github.com/dotnet/core/blob/master/roadmap.md
