### ISSUE TITLE
Possibility to host locally a Lambda function via the new Mock Tool

### ISSUE THREAD

**Issue by Kralizek** [aws/aws-lambda-dotnet#359]
Hi!

I was thinking about playing around with the Lambda Mock tool.

Specifically I'd like to have the possibility to "host" the function like we do here: https://github.com/emgdev/lambda-local-runner

I imagine the user experience to be something like

1. developer develop a lambda function via the template
2. developer hits F5
3. browser starts with possibility to start an execution with given data
4. developer selects another tab ("hosting")
5. developer selects port number
6. developer hits "start hosting" button
7. an http server accepting request on the loopback interface on the selected port number is started
8. developer fires requests from another service towards the local endpoint

**Comment by normj** [comment]
I like it. 

Are you thinking hosting like an API Gateway or to be able to receive invoke calls from an SDK call?

Instead of spinning up another http server and configuring another port could use a resource path on the current http server to decide the functionallity? For example

http://localhost:5050/ - Is the current screen
http://localhost:5050/_sdk-invoke/ - responds to Lambda SDK invoke calls
http://localhost:5050/_api-gateway/<api-gateway-resource-path/ - Converts Http request to API Gateway request and invokes Lambda function
http://localhost:5050/_alb/<alb-resource-path/ - Converts Http request to Application Load Balancer request and invokes Lambda function

**Comment by Kralizek** [comment]
This would also work, but if you modify the path, it's more complicated from the caller application to switch behaviour.

Ideally it should be as easy as changing the service URL.

Also, how do you support multiple lambdas to be tested at the same time?

**Comment by normj** [comment]
Currently the tool doesn't have support for multiple Lambda at the same time.

**Comment by Kralizek** [comment]
I know that! What I meant is that if my solution has, say, two lambdas, each should have its own "mock tool" running, on its own port...

**Comment by ashishdhingra** [comment]
Closing this in favor of new issue https://github.com/aws/aws-lambda-dotnet/issues/1279.
