### ISSUE TITLE
Amazon.Lambda.Tools targets .Net Core 1.0 (LTS) rather than the current version .Net Core 1.1

### ISSUE THREAD

**Issue by nickheppleston** [aws/aws-lambda-dotnet#36]
I'm running the 'current' version of .Net Core (v1.1), however it would appear that the latest version of the Amazon.Lambda.Tools package (1.1.0-preview1) targets the LTS version of .Net Core (v1.0).

As a result, when trying to use the Lambda Tools from the command-line I am presented with the following error:

```
C:\Temp\Git\aws-cloudwatch-sdk-test>dotnet lambda --help
The specified framework 'Microsoft.NETCore.App', version '1.0.0' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\shared\Microsoft.NETCore.App
  - The following versions are installed:
      1.1.0
  - Alternatively, install the framework version '1.0.0'.

```
I resolved the issue by installing the LTS version (currently .Net Core 1.0.3) alongside v1.1 and the tooling now works.

Would it be possible to update the tooling to target v1.1? If this is as simple as updating _project.json_ ([here](https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.Tools/project.json)) then I would be happy to provide a pull request, however I am not sure whether there are any implications of this change that I'm not aware of.

**Comment by Kralizek** [comment]
By design choice, Lambda and other .NET Core based AWS product will support only LTS versions.

**Comment by nickheppleston** [comment]
Great, thanks for the feedback.

**Comment by normj** [comment]
Slight correction. Lambda only supports LTS versions but that doesn't mean all AWS products will only support LTS versions. AWS ElasticBeanstalk's AMIs have both .NET Core 1.0 and 1.1 installed. Lambda is different because in this case Lambda is essentially hosting a running .NET Core environment so we need to make sure that the environment being hosted for our users will have long term support.

**Comment by automagic** [comment]
Does Lambda support the just released 1.0.4?

**Comment by mrns** [comment]
Hello, I have a .NET Core project with some net452 dependencies. As per MS documentation, a .NET Core app can run on top of net452 with no issues and indeed, I was able to get a working ,NET Core app by targeting net452. Now, I am having trouble using libraries targeted to .NET Core because some of them target netstandard1.3, some other target netcoreapp1.0 and so on, which causes incompatibility issues. This is the case with AWS .NET Core libraries for instance, how am I suppose to use libraries if there are so many different flavors of the same ".NET Core" apps. Is this something that can be resolved by changing some config or is it an MS design issue?

**Comment by dbvance** [comment]
Does the "here is a matrix of each .NET Standard version and each specific area it runs on" section of https://docs.microsoft.com/en-us/dotnet/articles/core/porting/libraries help?

**Comment by InsidiousForce** [comment]
@normj Also, it looks like Microsoft about 15 days ago added LTS* to 1.1 on this page: https://www.microsoft.com/net/core/support so maybe AWS will support this in Lambda
