### ISSUE TITLE
Update or Add Visual Studio Template to Include DI and Config for .NET Core

### ISSUE THREAD

**Issue by tonysneed** [aws/aws-lambda-dotnet#363]
I wrote a blog post on how to add .NET Core dependency injection and configuration to an AWS Lambda Function project: 
https://blog.tonysneed.com/2018/12/16/add-net-core-di-and-config-goodness-to-aws-lambda-functions/.

I would be happy to contribute a PR for updating the existing Visual Studio template for the AWS Lambda project so that it includes these mechanisms, which are quite important for .NET Core devs.

**Comment by normj** [comment]
I would recommend creating a new template so users can choose if they want to start with a barebones project or have the DI framework which I think would be very valuable.

To avoid increasing the deployment bundle, which could increase cold start, it might be better in the csproj file to reference the `Microsoft.NET.Sdk.Web` SDK and `<PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.5" />` instead of the individual packages. This way the DI assemblies won't be part of the deployment bundle and they will use the prejitted assemblies in the Lambda environment.

**Comment by Kralizek** [comment]
@tonysneed I hope you don't mind suggesting my own library and the related templates for your case.
Few other people have been using it in production. It can still be improved but it definitely serves its purpose.

https://github.com/Kralizek/AWSLambdaSharpTemplate/

**Comment by tonysneed** [comment]
@normj I also think it's a good idea to create a new template with DI and config.  I'll also implement your suggestion for updating the SDK and package references.

To get started should I sign a CLA?

**Comment by tonysneed** [comment]
Submitted PR #371 for this issue.

**Comment by ganeshnj** [comment]
Lambda Annotations library is out in preview. Please check https://www.nuget.org/packages/Amazon.Lambda.Annotations/0.5.0-preview

If you any feedback, feel free to create an issue.
