### ISSUE TITLE
Lambda@Edge Events Package

### ISSUE THREAD

**Issue by ghartsho** [aws/aws-lambda-dotnet#433]
I don't see a NuGet package with Lambda@Edge event models. (Similar to Amazon.Lambda.S3Events, Amazon.Lambda.DynamoDBEvents, etc..)

I've only seen Node examples of @Edge functions when I look around online but from the Lambda console it looks like you can deploy functions in any language. I'm still in very early stages of development for my app and would be happy to create a PR for whatever I end up using but was just wondering if there's already a package in the works.

I'll be rolling my own in the meantime based on this: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-event-structure.html

**Comment by klaytaybai** [comment]
@ghartsho, thanks for offering a PR.  That would be appreciated.

**Comment by ghartsho** [comment]
.Net Core runtime isn't currently supported unfortunately

**Comment by geoffrey-ge-carsalesnetwork** [comment]
still can't find a nuget package for

**Comment by gscpw** [comment]
Any reason why this has been closed instead of leaving the ticket open to track interest in this?

**Comment by normj** [comment]
What is the purpose of a LambdaEdge .NET event package since you can't write a LambdaEdge function in .NET? If the goal was escalate interest for .NET support for LambdaEdge functions the maintainers of this repository have no control or influence of that happening. You would need to influence the CloudFront and Lambda teams in someplace like https://repost.aws/.
