### ISSUE TITLE
Lambda tool aspnet version check does not resolve MSBuild parameter

### ISSUE THREAD

**Issue by aprooks** [aws/aws-lambda-dotnet#441]
I have a hybrid setup to allow publishing AspNet as a docker image and packaged with lambda tools.

```
<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>netcoreapp2.1</TargetFramework>
        <AWSProjectType>Lambda</AWSProjectType>
    </PropertyGroup>

    <PropertyGroup>
        <!--Fixes AspnetVersion for lambda -->
        <AspNetVersion Condition="$(lambda)!=''">2.1.6</AspNetVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.App" Version="$(AspNetVersion)" />
<!-- other stuff --> 
```

lambda tools version 3.2 throw error `Project is referencing version $(AspNetVersion) of Microsoft.AspNetCore.App which is newer than 2.1.6, the latest version available in the Lambda Runtime environment. Please update your project to use version 2.1.6 and then redeploy your Lambda function.`

Tools version rolled back to 3.1.2 build properly

**Comment by klaytaybai** [comment]
Hi @aprooks, I think you're going to need to use custom runtimes.  Take a look at this [custom runtime sample repository](https://github.com/normj/LambdaNETCoreSamples/tree/master/CustomRuntimeAspNetCore) that Norm put together.

**Comment by aprooks** [comment]
Hi @klaytaybai I'm not sure why you are suggesting using custom runtime. I'm using fully supported 2.1.6 runtime version, but specify it via MsBuild variable.

**Comment by normj** [comment]
Can you set the switch `--disable-version-check` to `true` when you execute your `dotnet lambda` command. This check used to be needed with older versions of the .NET Core SDK. Otherwise you would get confusing error messages when your dev machine was running a newer patch version then was currently running in Lambda. I just confirmed that condition does not happen anymore with the latest .NET Core SDK. I'll remove the check in the next version so you won't have to pass in `--disable-version-check`

**Comment by aprooks** [comment]
Hi Norm, 
thank you for this workaround, it works as is with Lambda tools version 3.2 now
