### ISSUE TITLE
Request: defaults for `dotnet lambda package` (-c Debug and -f netcoreapp1.0 or empty if 1 target)

### ISSUE THREAD

**Issue by FLGMwt** [aws/aws-lambda-dotnet#46]
It seems that it's common for first-class `dotnet` verbs such as `publish` and `build` to default `--configuration` to `Debug`. I think it would make sense for `dotnet lambda package` to do the same. 

Additionally, it would be nice to allow for `--framework` to be optional when only one TargetFramework is defined in the project. `publish` handles this without arguments. And is it meaningful to have a lambda project with two target frameworks?

**Comment by normj** [comment]
I was nervous about adding any defaults in the tooling especially while the project system is going through such big changes. That was one of the reasons for the [aws-lambda-tools-defaults.json](https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.Tools#user-content-manage-command-arguments-with-aws-lambda-tools-defaultsjson) file so that the defaults would reside with the code and not in the tooling.
