### ISSUE TITLE
Warning NETSDK1071 during build of a dotnet lambda

### ISSUE THREAD

**Issue by ckuetbach** [aws/aws-lambda-dotnet#463]
There is a warning message show during the build of the example:
```
C:\Program Files\dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets

(153,5): warning NETSDK1071: Ein PackageReference-Verweis auf "Microsoft.AspNetCore.App" 
hat die Version "2.1.4" angegeben. Die Angabe der Version dieses Pakets wird nicht empfohlen. 
Weitere Informationen finden Sie unter https://aka.ms/sdkimplicitrefs. 
```
Steps to reproduce:

1. Install the templates `dotnet new -i Amazon.Lambda.Templates::*`
2. Create a project `dotnet new serverless.AspNetCoreWebApp`
3. build the prooject `dotnet build`

I believe, there is no bug within the software itself, because the hard reference to a version is needed to ensure the conmpaibility between .net core and the AWS lambda environment, but it looks like a buildproblem and may scare devs.

I have a derived example project with a terraform build process for AWS lambda, and tried to fix this Issue, but I am not sure, if i would get into compatibility issues.
https://github.com/d-velop/dvelop-app-template-cs/pull/22

**Comment by normj** [comment]
In later versions of the .NET Tooling we no longer do this validation because the .NET Core team have improved how they package ASP.NET Core projects. So if you are using the latest version of the tooling you no longer have to have the version attribute. I'm planning in a future version of `Amazon.Lambda.Templates` to update the templates to remove the version attribute.
