### ISSUE TITLE
Library like "function-shield" to improve lambda security

### ISSUE THREAD

**Issue by niraj-bpsoftware** [aws/aws-lambda-dotnet#477]
I have just come across a library that does a fabulous job of improving lambda security

[function-shield](https://www.puresec.io/function-shield)

This library has been suggested as example in SAR documentation as well.

Unfortunately, this library is not .net enviornment.

Does anyone know if we have similar library for .NET?

**Comment by klaytaybai** [comment]
Hi @niraj-bpsoftware, I'm going to close out this issue because GitHub is not our preferred place for such discussions.  Please check out the AWS Forums for [Lambda](https://forums.aws.amazon.com/forum.jspa?forumID=186) or .[NET Development](https://forums.aws.amazon.com/forum.jspa?forumID=61) or go to StackOverflow.
