### ISSUE TITLE
"Default" category's log level shoud be used when category does not match

### ISSUE THREAD

**Issue by wdolek** [aws/aws-lambda-dotnet#521]
## Description

Current AWS Lambda library logging differs from usual .NET Core logging implementation. Difference is in how `Default` log level category is handled.

In .NET Core:

- `Default` category is used for any logger, which name doesn't match other declared categories
- if `Default` is not set and category does not match, minimum level is `Information`

You can read more about logger configuration here: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1).

### Use "`Default`" category if no match

1. Use and load following configuration:

```json
{
  "Lambda.Logging": {
    "LogLevel": {
      "Default": "Warning",
      "System": "Warning"
    }
  }
}
```

2. Using `ILoggerFactory`, create logger with name `Dummy` (not matching `System`)
3. Try to log debug event

#### Expected result
- No message logged, default logging (for categories not matching) is set to `Warning`

#### Actual result
- Message logged - no category match -> any level is enabled: [LambdaLoggerOptions.cs:L250](../blob/master/Libraries/src/Amazon.Lambda.Logging.AspNetCore/LambdaLoggerOptions.cs#L250)

### Using minimum log level `Information` when "`Default`" category not set

1. Use and load following configuration

```json
{
  "Lambda.Logging": {
    "LogLevel": {
      "System": "Warning"
    }
  }
}
```

2. Using `ILoggerFactory`, create logger with name `Dummy` (not matching `System`)
3. Try to log debug event

#### Expected result
- No message logged, default logging (in code) is set to `Information` (If config is missing, we don't want _slow down_ app with trace and debug events logging)

#### Actual result
- Message logged - no category match -> any level is enabled: [LambdaLoggerOptions.cs:L250](../blob/master/Libraries/src/Amazon.Lambda.Logging.AspNetCore/LambdaLoggerOptions.cs#L250)

## Conclusion

This is **breaking** change of course, however it will make life easier by adjusting to standard .NET behavior. (Yes, I spent some time struggling with using "my normal logging config" in Lambda)

**Comment by madmox** [comment]
After reviewing the source code, I suspect the lambda logger implementation is not standard-compliant in multiple ways, one of which explains the observed issue:

**Lambda logger LogLevel categories**
.NET LogLevel categories in config are actually category **prefixes**. They are matched if the log's actual category **starts with** the specified category (`Default` being the fallback). Lambda logger seems to use explicit wildcards in category names (e.g. `System.*` instead of just `System`), which is not compatible with .NET implementation.

**Lambda logger doen't override the default logging config section**
If you have an `appsettings.json` file with the following content:
```json
{
  "Logging": {
    "LogLevel": { "System": "Warning" },
    "Lambda.Logging": {
      "LogLevel": { "System": "Information" }
    }
  }
}
```
Logs with the `System` category will be logged only if their level is >= `Warning`, although [the documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1#configuration) states:
> If levels are specified in `Logging.{providername}.LogLevel`, they override anything set in `Logging.LogLevel`.

This seems to indicate that lambda logger is not wired correctly to the root logging provider.

**Logging provider config section name is not standard**
.NET logging provider config sections are always named after the suffix used in extension methods, e.g. :
* `AddConsole` -> provider config section name is `Console`
* `AddDebug` -> provider config section name is `Debug`
* `AddEventSource` -> provider config section name is `EventSource`
* etc.

Lambda logger uses a custom name `Lamda.Logging`, where it should use `LambdaLogger` instead (because the extension method is named `AddLambdaLogger`).

**Comment by wdolek** [comment]
@madmox, yeah, this is very custom implementation - my attempt here is to make it as similar with framework as possible. Still it lacks some features (e.g. as you stated `Logging.{providerName}.LogLevel`), but at least it is closer to what is common in .NET universe.

Regarding namespace prefixes, please check my other ticket: #519 (PR #520 respectively).

**Comment by normj** [comment]
PR has accepted and released.
