### ISSUE TITLE
Required library libhostfxr.so could not be found

### ISSUE THREAD

**Issue by ckuehl** [aws/aws-lambda-dotnet#573]
Related to #446, I'm seeing an issue when setting `--msbuild-parameters /p:PreserveCompilationContext=true` at the end of my `dotnet lambda deploy-serverless` command. I am using Amazon.Lambda.RuntimeSupport to run a .Net Core 2.2 app. When executing the Lambda function, I receive the following error:

```
A fatal error occurred, the required library libhostfxr.so could not be found.
If this is a self-contained application, that library should exist in [/var/task/].
If this is a framework-dependent application, install the runtime in the default location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location.
```

I need this set as I use the https://github.com/toddams/RazorLight library for some of our HTML email templates. Is there a way to use `p:PreserveCompilationContext` successfully with .Net Core 2.2 and Lambda?

**Comment by normj** [comment]
Assuming your created your Custom Runtime Lambda project from one of our templates check out the `aws-lambda-tools-defaults.json` file and see that it also has a value for `msbuild-parameters` set to **-self-contained true**. An awkward situation is when you set `--msbuild-parameters` on the command line it replaces what is set in `aws-lambda-tools-defaults.json` so the self contained switch doesn't get included.

Can you either include `--self-contained true` to the value you are setting for `--msbuild-parameters` or add `/p:PreserveCompilationContext=true` to `msbuild-parameters` in `aws-lambda-tools-defaults.json`.

Due to an old quirk from the .NET Core 1.0 days and the fact you are using razor pages with your Lambda function you also might need to set the runtime with msbuild parameters. To do that add `-r rhel.7.2-x64` to the msbuild parameters string. Now that .NET Core 1.0 is officially deprecated I plan on fixing that old quick.

**Comment by ckuehl** [comment]
Awesome - that seems to have fixed it. I wasn't aware that the values would override each other, so placing both flags in the `aws-lambda-tools-defaults.json` file worked. Thanks for the help!
