### ISSUE TITLE
Possible bug when assuming role while having existing credentials 

### ISSUE THREAD

**Issue by sonicjolt** [aws/aws-lambda-dotnet#62]
Hi aws-lambda-dotnet team,

We believe we might have found a minor bug when assuming role with the AWS CLI, and then running `dotnet lambda <command> ...`

Normally when we run our assume-role script, and then running for instance `aws s3 ls`, where the host-machine has AWS credentials in ~/.aws/credentials, these credentials are not used, but instead the expected "assume-role"-credentials.

But when we use the same script, and then the subsequent "dotnet lambda <command>", it is still loading the credentials from ~/.aws/credentials. 

If you look at: http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html under the section "Configuration Settings and Precedence", it clearly states that the precedence should be "2. Environment Variables" and then "3. The AWS Credentials File".

It seems that the aws-lambda-dotnet tooling is not following this precerence from the AWS CLI. And still using the ~/.aws/credentials, eventhough there are Environment credentials in the scope.

We have verified this by removing the credentials-file - and then assume-role works as expected.

If you need further details, let us know.

Thanks

**Comment by normj** [comment]
What does your assume role script do? I'm guessing it puts the credential information in environment variables.

If that is the case unfortunately the .NET SDK, which the lambda tooling is based on, has a different precedence order then the AWS CLI. The .NET SDK looks at environment variables after it has checked for a default profile. The difference is due to the fact that .NET SDK supported environment variables later then the profiles and putting things ahead in the precedence chain causes a breaking change.

**Comment by sonicjolt** [comment]
Alright, then it's clearly not a bug. Is this documented anywhere, or, perhaps it should be ?

**Comment by normj** [comment]
I double checked in the .NET SDK user guide and it is not explain as cleanly as the CLI is for its precedence. I have pinged the doc writer of the guide to get a similar precedence list in the .NET SDK.

We are working in the .NET SDK the ability to assume roles configured in the credentials file. When that is released will that work for you?
