### ISSUE TITLE
Unable to load type 'AWSLambda2.Function' from assembly 'bootstrap' with example project

### ISSUE THREAD

**Issue by ab-tools** [aws/aws-lambda-dotnet#649]
I'm trying to get the AWS Lambda .NET Core 3.1 example project to run.

Here are the steps I do:
1. Create a new solution including project with "AWS Lambda Project (.NET Core - C#)".
2. Select "Custom Runtime Function" as Blueprint.
3. Without changes to the project code, just right-click on the project and select "Publish to AWS Lambda...".
4. Enter values in the wizard as seen in the attached "aws-lambda-tools-defaults.json" (inside the [AWSLambda2.zip](https://github.com/aws/aws-lambda-dotnet/files/4535324/AWSLambda2.zip)).
=> The deployment is successful without any error messages as you can see in the [AwsLambdaDeployLog.txt](https://github.com/aws/aws-lambda-dotnet/files/4535325/AwsLambdaDeployLog.txt).

When I now execute the Lambda function I always get the message:
Unable to load type 'AWSLambda2.Function' from assembly 'bootstrap'.

Here is also the execution log:
[AwsLambdaTestLog.txt](https://github.com/aws/aws-lambda-dotnet/files/4535326/AwsLambdaTestLog.txt)

What am I doing wrong here?

Thanks in advance
Andreas

**Comment by normj** [comment]
Looks like there is an issue in the VS Toolkit when you attempt to deploy a Custom Runtime Function blueprint that targets .NET Core 3.1 the Lambda runtime drop down box in the wizard defaults to .NET Core 3.1 Lambda runtime instead of the Custom Runtime option. The workaround for when you want to use a .NET Core 3.1 Custom runtime is be sure to explicit set Lambda runtime drop down box to .NET Core Custom Runtime.

Out of curiosity what is your use case for wanting to use the Custom Runtime template for .NET Core 3.1 now that Lambda natively support 3.1. I don't anticipate the custom runtime blueprint having a lot of value right now since Lambda natively supports the latest version of .NET Core. Only reason I can think to use it is if you want to try a preview of .NET 5.

**Comment by ab-tools** [comment]
Thanks for your reply on this, Norm!

Indeed, using the .NET Core 3.1 Lambda runtime directly makes more sense.
I was following a tutorial which still pointed to the "Custom Runtime" option. ;-)

Thanks again
Andreas
