### ISSUE TITLE
Logger Warning on APIGateway should be repressed 

### ISSUE THREAD

**Issue by richardkeller411** [aws/aws-lambda-dotnet#693]
https://github.com/aws/aws-lambda-dotnet/blob/85dd6e164c324120535815e02c30e3ae2e5d72f3/Libraries/src/Amazon.Lambda.AspNetCoreServer/APIGatewayHttpApiV2ProxyFunction.cs#L94-L97

This pollutes Cloudwatch for users of API Gateway with Warnings that aren't really warnings.   I think this should be changed to a LogDebug..

Unless someone has another way to suppress.

**Comment by NGL321** [comment]
Hi @richardkeller411,

Thank you for reporting this. Your thinking here makes sense, its certainly worth considering.
That said, this is more of a feature request since the code is functioning as intended.

Someone will update this issue with an update (or reasoning as to why to keep the functionality).

Thanks!
😸 😷

**Comment by duaneking** [comment]
Any updates?

**Comment by normj** [comment]
Version `6.0.1` of Amazon.Lambda.AspNetCoreServer is out with this log message removed.

**Comment by duaneking** [comment]
The error itself had value; Removing it was the wrong choice, we just wanted a way to turn it off when we are not debugging.

**Comment by ja-nick** [comment]
I'm seeing this warning on version 7.2.0.
