### ISSUE TITLE
Lamdba exits on any DynamoDB async function

### ISSUE THREAD

**Issue by UrizielTSD** [aws/aws-lambda-dotnet#714]
I got the problem that my Lambda always exits whenever any async function call is made.

Visual Studio Invoke log (Cloudwatch is the same):
![image](https://user-images.githubusercontent.com/27346238/89420993-c5cbe780-d733-11ea-8669-6d2faa719c61.png)

Here is the code part:
![image](https://user-images.githubusercontent.com/27346238/89421113-eb58f100-d733-11ea-90b4-07d0612de97f.png)

Before someone ask:
![image](https://user-images.githubusercontent.com/27346238/89421758-b8fbc380-d734-11ea-942d-c9fad4adc9d8.png)
I gave it full permission.

When I debug it locally it works perfectly fine. But inside AWS it always exits.
AWSSDK.DynamoDBv2 3.3.106.42
Any ideas?

**Comment by ashishdhingra** [comment]
Hi @UrizielTSD, 

Thanks for reporting the issue. I will try to reproduce the issue and update you on this thread.

It would be helpful if you could provide more information in the following format along with the scenario details:



## Expected Behavior



## Current Behavior






## Possible Solution



## Steps to Reproduce (for bugs)





## Context



## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj:


Thanks,
Ashish

**Comment by ashishdhingra** [comment]
Hi @UrizielTSD,

Good morning.

Could you please confirm if the above async call _context.LoadAync() is invoked from a separate helper method from the Lambda function handler? If yes, then try to temporarily move the logic out from this method and execute this in the Lambda function handler method. I suspect the issue is due to the way Lambda runtime execution environment works. You might need to use Task.WaitXXX() methods to stop Lambda function from returning until DynamoDb async call completes.

Thanks,
Ashish

**Comment by UrizielTSD** [comment]
Hello Ashish,

it was not, the function was async void. Changing it wo async Task fixed the issue.

This:
![image](https://user-images.githubusercontent.com/27346238/89632826-275e9400-d8a3-11ea-99e3-fd45b5cada46.png)

To this:
![image](https://user-images.githubusercontent.com/27346238/89632805-1f065900-d8a3-11ea-8a09-52a8ca75989d.png)
fixed it.

Thanks Ashish!
Alex
