### ISSUE TITLE
.NET 5 support?

### ISSUE THREAD

**Issue by andyfurniss4** [aws/aws-lambda-dotnet#727]
Apologies if this has been asked before, feel free to close and point me to the answer if so. I have had a look but couldn't find the answer anyway.

.NET 5 is not marked as an LTS release: https://devblogs.microsoft.com/dotnet/introducing-net-5/

I know the Lambda team's policy is to only support .NET LTS releases but will that apply to .NET 5 as well or will an exception be made considering it's quite a big one (the unification of .NET Core and .NET Framework)? Would be a shame if we had to wait until late 2021/early 2022 for the next supported .NET version (.NET 6) and all the extra goodies that come with it.

**Comment by henalbrod** [comment]
I'm curious too about this topic, especially since waiting for next LTS (2021) sounds like a very bad (business) idea.

**Comment by normj** [comment]
It is the Lambda service team's policy to support LTS versions of runtimes. We, the AWS .NET Team, are trying to work through our alternatives to see how best we can support .NET 5 with Lambda as we know there is a lot of excitement for it.

Out of curiosity from running .NET in Lambda perspective what are people most interested in with .NET 5? This helps me push priorities.

**Comment by petarrepac** [comment]
Fast startup, low footprint, and lower memory usage
static compilation of .NET (ahead-of-time – AOT)
Java interoperability - this could be a "killer feature"

**Comment by ashishdhingra** [comment]
Hi @andyfurniss4,

Good afternoon.

Looks like @normj had provided input on this question. Please advise if we could close this issue.

Thanks,
Ashish

**Comment by xdaDaveShaw** [comment]
> Out of curiosity from running .NET in Lambda perspective what are people most interested in with .NET 5? This helps me push priorities.

I really want to move to C# 9 for Records, new Json Serialization, Nullable Type Annotations, F# 5 - in that order

**Comment by bjorg** [comment]
I'd be curious to see how far we can get with a custom runtime instead of native .NET 5 support. Especially the link trimmer should be able to cut out a lot of unnecessary code, reducing the package size. If the custom runtime approach is not suitable, then I would be very much in favor of native .NET 5 support. As others have pointed out, the primary driver would be the new C# language features.

**Comment by martincostello** [comment]
A custom runtime should work, but there's a bug in the .NET runtime in 5.0 RC1 that means it doesn't work in AWS Lambda (see #730). Should be good once RC2 is released.

**Comment by xdaDaveShaw** [comment]
Is using and maintaining a custom runtime much of an overhead for teams? I've not looked into it recently, last time it seemed a lot of effort, but that was for CoreRT.

E.g. setting one up, using it, updating it, etc?

What about support for them?

**Comment by martincostello** [comment]
From personal experience, the only ongoing overhead I have is bumping the NuGet package(s) and SDK once a month to pick up the latest fixes and/or security patches and then redeploying.

Otherwise I think switching to a custom runtime took me about a day to refactor and test everything and plug in the `Amazon.Lambda.RuntimeSupport` package.

You have to write a little bit more code and keep it up-to-date, but you can use the latest features as soon as they're available. If you don't have the bandwidth to keep things updated etc., then you can use the built-in runtime but then you have to wait for however long it takes the AWS Lambda team to make the new runtime available amongst all their other project work.

For my use cases, I feel the overhead is worth being able to update on our own schedules, rather than be tied to AWS'.

YMMV.

**Comment by rlove** [comment]
We are currently moving from Oracle to Aurora Postgres, as they slowed our development down as we were unable to innovate with the latest technology.   Since it's Entity Framework Drivers for Oracle targeting .NET Core 3.X was just released.  We realized we need to stay on LTS because of them.    But LTS support can't come months later.  Given that I think .NET 5.0 is also a good exception to the LTS plan, as it is such a monumental shift in functionality.

**Comment by johan-lindqvist** [comment]
Any news on this now that .NET 5 is released?

**Comment by andyfurniss4** [comment]
My main interests are C# 9 and all the `System.Text.Json` updates.

**Comment by bjorg** [comment]
Keep in mind that you can use the Custom Runtime capability to use .NET 5 today: https://aws.amazon.com/blogs/developer/net-core-3-0-on-lambda-with-aws-lambdas-custom-runtime/

I haven't tried it yet, but with code trimming, which is new in .NET 5, the experience should be a lot better than with .NET Core 3.0.

**Comment by jstallm** [comment]
> It is the Lambda service team's policy to support LTS versions of runtimes. We, the AWS .NET Team, are trying to work through our alternatives to see how best we can support .NET 5 with Lambda as we know there is a lot of excitement for it.
> 
> Out of curiosity from running .NET in Lambda perspective what are people most interested in with .NET 5? This helps me push priorities.

Does this mean that running lambda apps with .NET 5 will only be supported once .NET 5.0 moved from "current" to "LTS"?

**Comment by martincostello** [comment]
.NET 5.0 will never be LTS. .NET 6.0 will be the next LTS version.

**Comment by jstallm** [comment]
> .NET 5.0 will never be LTS. .NET 6.0 will be the next LTS version.

What exactly does this mean with respect to lambdas and their support for using .NET 5.0?

**Comment by bjorg** [comment]
It means we should not expect support for .NET 5 on Lambda since it's not going to be LTS.

**Comment by jstallm** [comment]
> It means we should not expect support for .NET 5 on Lambda since it's not going to be LTS.

Thank you @bjorg . If this is the conclusion, shouldnt this issue be closed with this as the answer?

**Comment by andyfurniss4** [comment]
I raised this knowing that .NET 5 was not LTS and that the AWS team only supports LTS. I was wondering if an exception would be made due to the magnitude of the release and the fact that the next LTS won't be until the end of 2021. Thing is, we haven't had an explicit "yes" or "no" yet so I do not think we should close this yet. The .NET 5 release has come and gone (just like it did for 3.1) and we don't have Lambda support but that doesn't mean A) they aren't working on it or B) they aren't planning to.

If the AWS guys have decided not to support .NET 5 and they tell us this then sure, let's close this. We'll just have to wait another 12-18 months for the next supported .NET version.

**Comment by Kralizek** [comment]
Truth is that, considering the pace Microsoft has decided to give to .NET, it doesn't make sense to wait for an LTS release every other year. Because even Current release smells like LTS when it's bound to stay around for 15 months (1 year + 3 months support).

I would be fine if AWS defined LTS and Current runtimes so that we customers could decide on which path we want to stay.

Honestly, I would be fine with a pre-cooked custom runtime for runtimes on the Current path.

**Comment by martincostello** [comment]
> Honestly, I would be fine with a pre-cooked custom runtime for runtimes on the Current path.

You say that, but others might not be as enthusiastic to get a notification from AWS in November 2021 telling them they have 3 months to update from 5.x to 6.0 before their Lambdas drop out of all support from AWS.

A lot can change in a year and suddenly a team might not have the bandwidth to react to the need to update a Lambda that might not have been touched for months to keep in support that was previously being done on their behalf by Amazon updating the hosted runtime as needed without having to think about it.

Sure, there could be a current pre-cooked current runtime with loads of warnings and caveats on it, but that would come with its own support complexities and nuances users would need to understand.

It would be great if Lambda supported all new major versions of .NET as of the day they're released by Microsoft, but I imagine the practicalities of doing that at their scale are why things are the way they are right now.

If you really, really want to be on the cutting edge and upgrade as soon as possible and support things yourself and do your own thing and be accept all the consequences, then that's kind of what custom runtimes are for.

**Comment by genifycom** [comment]
Problem is, we are not obviously on the cutting edge. .NET Core moves fast and has been remarkably stable. Look in NuGet right now and packages are there for 5.0.0. They are for public consumption now.

While I have not tried to upgrade a DotNet Core 3.1 project to DotNet 5, so far, I have not run into any major issues in just upgrading (e.g. from 2.1 to 3.1).

DotNet 5 may be a different beast, but the custom runtimes for me are for more unusual environments like C++ Lambda.

I would rather have the updates and move to DotNet 5 Lambda sooner rather than later. 2020 has proven that a year is a loooong time :-)

**Comment by Kralizek** [comment]
I see where you're coming from @martincostello.

But this is the kind of choice that should be on customers: going Current or LTS.

AWS not releasing runtimes on Current because a customer who chose it could find itself in trouble for it is a distortion of the responsibility AWS has towards its customers. They should provide the tools and let everybody decide which tool is best suited to them.

Adding to what @genifycom said, Lambda functions are usually very simple and most of the times their code don't rely on features specific of a framework so that it makes it hard to move from one major version to another (obviously there are anomalies).

In my company we have tens of functions and most of the time we upgrade them with a folder-wide find/replace (it was a bit more complex when we had to remove the specific LambdaTools property from the project file).

**Comment by tmitchel2** [comment]
I too would like to see transitive support for dotnet 5 until an LTS version is available. (this happened in the past with another version)

The only options available at the moment are:
- stay with dotnet core 3.1 and wait until dotnet 6 :(
- use a custom runtime (which in itself would be fine, however, due to lack of sufficient native AOT in dotnet 5 the startup times would likely be impacted to the extent that it would turn developers off the idea https://medium.com/@zaccharles/benchmarking-lambdas-new-custom-runtime-for-net-core-43ea79b5a35a)

**Comment by martincostello** [comment]
Zac followed up that original post with more details about how to improve the startup performance for the custom runtime: https://medium.com/@zaccharles/net-core-3-0-aws-lambda-benchmarks-and-recommendations-8fee4dc131b0

**Comment by bjorg** [comment]
I hope he posts a .NET 5 version, because there are a lot of compilation improvements in .NET 5 that did not exist in .NET Core 3.1, such as code trimming, which would be very useful with the custom runtime.

**Comment by snelson25** [comment]
Serverless web application (ASP.NET Core Web API) using Microsoft Identity Web.

**Comment by SeidChr** [comment]
Seems like its not such a big deal to write a .net 5 Lambda thanks to the nice compiler features.
I have created a very simple sample lambda custom runtime:
https://github.com/SeidChr/AwsLambdaDotnet5CustomRuntime/

With ReadyToRun publishing it reduced the startup time to about 300ms (@128mb) 🤩

Official support would still be nice though :)

**Comment by bjorg** [comment]
@SeidChr That's pretty good! How big is the Lambda package?

**Comment by martincostello** [comment]
You can get a _"more supported"_ .NET 5 lambda by using the [Amazon.Lambda.RuntimeSupport](https://www.nuget.org/packages/Amazon.Lambda.RuntimeSupport/) NuGet package as documented [here](https://aws.amazon.com/blogs/developer/announcing-amazon-lambda-runtimesupport/) than by trying to do the HTTP calls to the runtime API yourself.

**Comment by SeidChr** [comment]
> @SeidChr That's pretty good! How big is the Lambda package?

smallest I could get was just below 9mb

**Comment by martincostello** [comment]
For those who've not seen it, there's an alternate approach available for .NET 5 using containers now available: https://aws.amazon.com/blogs/developer/net-5-aws-lambda-support-with-container-images/

**Comment by normj** [comment]
As @martincostello mentioned we are supporting .NET 5 via the Lambda container support since .NET 5 is not a LTS. We tried to make the experience as familiar as possible to the existing experience but still provide full access to the features containers give. I recommend giving it a try. Don't make a determination based on the first invocation as Lambda has smart caching going on behind the scenes that improve the performances of subsequent invokes. 

There won't be a managed runtime for .NET 5 since it not an LTS and will only be supported by Microsoft for 15 months. I had left this issue open because I knew we working on this effort and now that it is out I'm going to close it.

**Comment by kamyker** [comment]
Removed hosting part, LitJson and bunch of other things, without trimming 30mb, with 13mb. Start up from net core 3.1 went down from 3s to 1s.

```
<PropertyGroup>
	<OutputType>Exe</OutputType>
	<TargetFramework>net5.0</TargetFramework>
	<PublishReadyToRun>true</PublishReadyToRun>
	  <PublishTrimmed>true</PublishTrimmed>
	<InvariantGlobalization>true</InvariantGlobalization>
	<TrimMode>link</TrimMode>
	<EnableUnsafeBinaryFormatterSerialization>false</EnableUnsafeBinaryFormatterSerialization>
	<EnableUnsafeUTF7Encoding>false</EnableUnsafeUTF7Encoding>
	<EventSourceSupport>false</EventSourceSupport>
	<DebuggerSupport>false</DebuggerSupport>
</PropertyGroup>
```
https://github.com/kamyker/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.RuntimeSupport

Nuget: https://www.nuget.org/packages/KS.Amazon.Lambda.RuntimeSupport.Net5Only/

**Comment by bjorg** [comment]
That's pretty cool! Thanks for sharing.

**Comment by bjorg** [comment]
@kamyker What changes did you make to `Amazon.Lambda.RuntimeSupport` to label it .NET 5 only? I'm adding support to LambdaSharp.NET for self-contained .NET 5 Lambda functions. Any advice on things to look out for would be much appreciated!

**Comment by bjorg** [comment]
Looking at the diff here, is there anything that could be pushed upstream?
https://github.com/aws/aws-lambda-dotnet/compare/master...kamyker:master

**Comment by bjorg** [comment]
Here's some food for thought. I deployed the same code once using the .NET Core 3.1 runtime and once as a self-contained .NET 5 image using the `provided.al2` runtime.

I then ran each 40 times and collected their warm execution durations. Both functions were given 1792MB of RAM so they get access to 100% of the vCPU.

|Measurement|.NET Core 3.1 Runtime|.NET 5 Self-Contained|
|---|---|---|
|Average (ms) |0.846ms|1.083ms|
|Min (ms)|0.720ms|0.830ms|
|Max (ms)|1.260ms|2.720ms|

This naïve test shows that self-contained .NET 5 is about 28% slower on average for this trivial case. I know a more exhaustive test would be require to solidify these preliminary findings. Assuming they hold, it would mean self-contained is no substitute for AWS providing runtime support.

Neither function used the _Ready-to-Run_ feature. Both function were compiled with _Tiered Compilation_ and _Quick JIT_ disabled.

Additionally, the .NET 5 self-contained function was linked with the following trimming options:
```xml
<PublishTrimmed>true</PublishTrimmed>
<InvariantGlobalization>true</InvariantGlobalization>
<TrimMode>link</TrimMode>
<EnableUnsafeBinaryFormatterSerialization>false</EnableUnsafeBinaryFormatterSerialization>
<EnableUnsafeUTF7Encoding>false</EnableUnsafeUTF7Encoding>
<EventSourceSupport>false</EventSourceSupport>
<DebuggerSupport>false</DebuggerSupport>
```

**Comment by SeidChr** [comment]
> Here's some food for thought. I deployed the same code once using the .NET Core 3.1 runtime and once as a self-contained .NET 5 image using the `provided.al2` runtime.
> 
> I then ran each 40 times and collected their warm execution durations. Both functions were given 1792MB of RAM so they get access to 100% of the vCPU.
> 
> Measurement	.NET Core 3.1 Runtime	.NET 5 Self-Contained
> Average (ms)	0.846ms	1.083ms
> Min (ms)	0.720ms	0.830ms
> Max (ms)	1.260ms	2.720ms
> This naïve test shows that self-contained .NET 5 is about 28% slower on average for this trivial case. I know a more exhaustive test would be require to solidify these preliminary findings. Assuming they hold, it would mean self-contained is no substitute for AWS providing runtime support.
> 
> Neither function used the _Ready-to-Run_ feature. Both function were compiled with _Tiered Compilation_ and _Quick JIT_ disabled.
> 
> Additionally, the .NET 5 self-contained function was linked with the following trimming options:
> 
> ```
> <PublishTrimmed>true</PublishTrimmed>
> <InvariantGlobalization>true</InvariantGlobalization>
> <TrimMode>link</TrimMode>
> <EnableUnsafeBinaryFormatterSerialization>false</EnableUnsafeBinaryFormatterSerialization>
> <EnableUnsafeUTF7Encoding>false</EnableUnsafeUTF7Encoding>
> <EventSourceSupport>false</EventSourceSupport>
> <DebuggerSupport>false</DebuggerSupport>
> ```

when I tested this in a normal lambda, it was alot faster.
could you maybe confirm my findings?
https://github.com/aws/aws-lambda-dotnet/issues/727#issuecomment-735846745

**Comment by bjorg** [comment]
You sure slimmed that down!!! 😁

**Comment by SeidChr** [comment]
> You sure slimmed that down!!! 😁

i focused on making it competitive with Typescript / JS lambdas

**Comment by bjorg** [comment]
@SeidChr @kamyker are you on the AWS Developer Slack #dotnet channel? If not, DM me on Twitter @lambdasharp with your email so I can have AWS admin invite you. Or we can continue the conversation here.

**Comment by kamyker** [comment]
1ms vs 1.3ms tests don't make much sense, try something more complicated that takes ~100ms. For me it runs 10-20% quicker with a lot smaller gc alloc when receiving 500kb jsons requests (from API Gateway) due to utf8json.

Anyway instead of trying to make as small as possible microservices I've started using one lambda function with some switch/cases on request enum type that's passed in header. X function instances are kept warm by other function. It's a lot simpler, now I have ApiDev and ApiProd fuctions and don't have to touch Api Gateway ever again.
