### ISSUE TITLE
AWS lambda function not able to read or use aws lamda layer dll in dot net core

### ISSUE THREAD

**Issue by suryasinghRateGain** [aws/aws-lambda-dotnet#789]
I have pushed custom dll or library project dll on aws lambda layer but not able to use the namespace present inside it ,inside a lambda function which use lambda layer ,it giving 500 error on request from url.I have used serverless template for lambda deployment

**Comment by ashishdhingra** [comment]
Hi @suryasinghRateGain,

Good morning.

Please share the details in the below format along with the sample code solution for reproducing the issue.



## Expected Behavior



## Current Behavior






## Possible Solution



## Steps to Reproduce (for bugs)





## Context



## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

Also kindly confirm if this is the same issue as https://github.com/aws/aws-lambda-dotnet/issues/776 reported earlier where you tried to use class library project referencing custom DLLs and the guidance was provided that the lambda layer feature is dependent on .NET runtime package store feature (more information at [Runtime package store](https://docs.microsoft.com/en-us/dotnet/core/deploying/runtime-store)).

Thanks,
Ashish
