### ISSUE TITLE
Question: send json payload?

### ISSUE THREAD

**Issue by dariusdamalakas** [aws/aws-lambda-dotnet#82]
The new templates look good. Thanks for all the work! Installed templates, compiled, and deployed. It's tricky to get them running though.   I'll add a list of things that got me puzzled. Some of them will not be issues, just an observation whilst using this for the first time. Was using empty function template.

1. For new starters, `readme.md` could go a bit extra at explaining necessary first steps. 
a) Need a default profile. `aws configure --profile <profile name>` does the trick. Use IAM roles (IMO, its ok to repeat that IAM roles is the good practice to follow)

b) Provide full command to deploy functions. It was unexpected that i was continuously being asked about the function name every time i wanted to deploy that. `aws-lambda-tools-defaults.json` should have `function-name` property set, otherwise deploy will always ask for func name.  A simple `"function-name": "func1"` would be enough in that file.

c) Maybe not that `aws-lambda-tools-defaults.json` is the default config, and will be loaded by default.  But if there is need, you can supply a different config. 
`dotnet lambda deploy-function --config-file <different config`

d) full command to run function. 
`dotnet lambda invoke-function func1 --payload "input_data"`

2. Default template takes `string` as input param. However, the assembly is configured with  `LambdaSerializerAttribute(typeof(JsonSerializer))`, which I understand tries to convert every input to JSON.  If we run func without params, func fails instead of getting a nullable string.  Why does this happen? 

 ````
 $ dotnet lambda invoke-function func1
Payload:
{
  "errorType": "JsonReaderException",
  "errorMessage": "Unexpected character encountered while parsing value: {. Path '', line 1, position 1.",
  "stackTrace": [
....
 ````

3. How to send JSON payload? 

Here's my attempt. Code:
 ````
     public class MyObject
    {
        public string Name {get;set;}
    }
    
    public class Function
    {
        public string FunctionHandler(MyObject input, ILambdaContext context)
        {
            if (input.Name == null)
                return "Name was empty. Provide input. {name:myvalue}";
            return input?.Name.ToUpper();
        }
    }
 ````

Execution.  
 ````
$ dotnet lambda invoke-function func1 --payload " "
Payload:
"Name was empty. Provide input. {name:myvalue}"
 ````

Attempt 2 with json payload
````
$ dotnet lambda invoke-function func1 --payload {"name":"value1"}
Error invoking Lambda function: Could not parse request body into json: Unexpected character ('n' (code 110)): was expecting double-quote to start field name
 at [Source: [B@6ddb5342; line: 1, column: 3]
````

4. Not related to anything above, but the way to get help for `aws` commands and `dotnet lambda` is different. For `aws` help always come as last param, for `dotnet lambda`,  `help` must come before any commands.   This is inconsistent behaviour. Personaly, `aws` approach is better, as it's easier to append `help` at the end, than in the middle.

E.g. to get help on `invoke-func` command:
`dotnet lambda --help invoke-func`

**Comment by normj** [comment]
Thanks for all the feedback.

1) The `dotnet new` templating engine has some new features coming out for post actions which will allow us to display the next steps like we did with the Yeoman generators. It is also on their roadmap for interactive mode so we can prompt for profile and region like we did in the Yeoman generators. It is still early days for the `dotnet new` templating engine but it seems like the right long term tool for the blueprints. Check out the templating github to see what features are coming and what we will be able to take advantage of. 
https://github.com/dotnet/templating

1b) I'm leary of defaulting the function name because I want to make sure developers can find there functions after they deploy them. I have seen many users that get lost when everything is already defaulted. We could add `"function-name" : ""` in the defaults file so it is more discover able that the can set it at that level.

1c) Not sure what you mean on that comment.

1d) Not sure what the question is.

I'll comment on the other parts later.

**Comment by normj** [comment]
2) Sounds like we should look into JsonSerializer passing along the null if no event arg is passed in.

3) The payload parameter can be a file path. I'd recommend writing your JSON to a file and use that.

4) I was aiming to be like the dotnet CLI over the aws CLI. I believe how we do help is similar to other commands in the dotnet CLI.

**Comment by PavelSafronov** [comment]
@dariusdamalakas, some more information about questions 2 and 3.

**Question 2**:

> Default template takes string as input param. However, the assembly is configured with `LambdaSerializerAttribute(typeof(JsonSerializer))`, which I understand tries to convert every input to JSON. If we run func without params, func fails instead of getting a nullable string. Why does this happen?

The `LambdaSerializerAttribute(typeof(JsonSerializer))` code is specifying that when serializing and deserializing objects, we're going to use the `JsonSerializer` to convert between JSON data and .NET types. This is because when data is passed to a Lambda function, it's passed as JSON, which then has to be converted to whatever input type you are using.

So, let's say your function for this question is expecting a string. If you don't specify a payload, AWS Lambda passes an empty JSON object `{}` to your function. Then `JsonSerializer` attempts to convert the JSON data {} to a string, and it obviously can't, so throws the error you see.

**Question 3**:

You can pass JSON data to your function by specifying JSON on the command-line, or in a file and reference that file. Below are examples of both approaches.

Pass JSON in the command line:
```
dotnet lambda invoke-function --payload "{\"Name\":\"value1\"}"
```

Pass JSON in a file:
```
dotnet lambda invoke-function --payload c:\Test\poco.txt
```
Contents of c:\Test\poco.txt
```
{ "Name" : "value1" }
```

As you can see the first approach is more complicated as it requires you to escape all of the double-quotes, hence why Norm was suggesting using a file.

**Comment by normj** [comment]
Closing this but feel free to reopen with more feedback
