### ISSUE TITLE
Community blueprints

### ISSUE THREAD

**Issue by Kralizek** [aws/aws-lambda-dotnet#86]
Hi,
I was looking for a statement or code of conduct regarding blueprints.

Specifically these questions:
* Can the community contribute to the blueprints by submitting PRs to this repository?
* What's needed for a blueprint to be available both as dotnet-new and in Visual Studio?
* Can a blueprint reference external packages? (e.g. Can I submit a blueprint referencing https://github.com/Kralizek/AWSLambdaSharpTemplate ?)

**Comment by normj** [comment]
That is a good question we haven't figured out yet. For blueprints that are just using our SDK that would be easier for us. But blueprints that are using community packages/frameworks we need a mechanism to make sure users know where to get support for those blueprints and their frameworks.

Let me think on it for a bit and I'll get back to you.

**Comment by normj** [comment]
So I think the answer for this is the [Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/) although our tooling doesn't integrate with that yet. If the blueprint is just using the AWS SDK and highly maintained third party packages, think Newtonsoft here, then we would consider a PR for it. Ultimately I don't think we want to do the effort in our tooling to distinguish between AWS and Community blueprints because that would be resolving Serverless Application Repository function. Just not sure when we will have the time to do that integration.
