### ISSUE TITLE
A "dll" get excluded from layer's zip archive when I run "dotnet lambda publish-layer". "Failed to compress file" error

### ISSUE THREAD

**Issue by GlebObodovsky** [aws/aws-lambda-dotnet#879]
## Description

I have a [manifest file](https://github.com/aws/aws-lambda-dotnet/files/6633092/manifest.txt) containing a reference to `Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions:2.2.0`.

When I run `dotnet lambda publish-layer` against it like:
dotnet lambda publish-layer lambda-layer `
	--package-manifest manifest.xml `
	--layer-type runtime-package-store `
	--s3-bucket lambda-layer-bucket `
	--framework netcoreapp3.1

I get:
`Failed to compress file: open dotnetcore\store\x64\netcoreapp3.1\microsoft.aspnetcore.server.kestrel.transport.abstractions\2.2.0\lib\netstandard2.0\Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.dll: The system cannot find the path specified.`
Even though, when I check the specified location, the file sits there ready to be archived. 

The complete [log](https://github.com/aws/aws-lambda-dotnet/files/6633111/log.txt)

The [artifact](https://github.com/aws/aws-lambda-dotnet/files/6633114/artifact.txt)

What's important to note is that for other NuGets and dependencies it works perfectly.

### Environment

* Package Id: amazon.lambda.tools
* Version: 5.1.3
* Commands: dotnet-lambda
* OS Info: Windows 10
* Build Environment: Powershell
* .NET SDK: 3.1.405

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @GlebObodovsky,

Good morning.

Thanks for posting the issue. Ideally this issue should have been opened in https://github.com/aws/aws-extensions-for-dotnet-cli repository since it appears to be related to .NET CLI extensions.

From the log it appears that `dotnetcore/store/x64/netcoreapp3.1/microsoft.aspnetcore.http.features/2.2.0/lib/netstandard2.0/Microsoft.AspNetCore.Http.Features.dll` is successfully included in the ZIP archive. Per log the file should be present in `C:\Users\Gleb\AppData\Local\Temp\devgleb-search-lambda-layer-637589402743382937\dotnetcore\store\x64\netcoreapp3.1\microsoft.aspnetcore.server.kestrel.transport.abstractions\2.2.0\lib\netstandard2.0\Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.dll`. Looks like the file path length of this file is `261` characters which is above the Windows limit of **260** characters. Are you able to confirm that the name of this file at the above path is NOT `Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.dl` (missing `l` at the end)? Assuming that this might be the issue you may try temporarily changing the TEMP folder location in current command prompt session:
```
set TMP=C:\temp 
set TEMP=%TMP% 
```
**Note:** The temporary directory must already exist.

For permanent solution, you may try allowing long path names in Windows Group Policy (kindly refer online articles on guidance).

Please let me know if this helps.

Thanks,
Ashish

**Comment by GlebObodovsky** [comment]
Hello Ashish!
Yes, the path was correct. I reduced the name of the layer from `devgleb-search-lambda-layer` to `devgleb-search-layer` and it helped. 

Thank you very much for your help @ashishdhingra
