### ISSUE TITLE
API Gateway Proxy: headers are case sensitive

### ISSUE THREAD

**Issue by kle-sd** [aws/aws-lambda-dotnet#904]
Same issue referenced in this go-sdk bug report. https://github.com/aws/aws-lambda-go/issues/117

APIGatewayCustomAuthorizerRequest should have some sort of way to access the headers without case sensitivity.

These variations should all work.

```
request.Headers.Get("authorization")
request.Headers.Get("Authorization")
request.Headers.Get("aUthoRization")

**Comment by ashishdhingra** [comment]
Hi @kle-sd,

Good afternoon.
 
Thanks for reporting the issue. Could you please provide the detailed steps and sample code solution to reproduce the issue, preferably in the below format? This would ensure we have complete information in place to discuss with the team.



## Expected Behavior



## Current Behavior






## Possible Solution



## Steps to Reproduce (for bugs)





## Context



## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

Thanks,
Ashish
